import {
  User,
  ImageIcon,
  Briefcase,
  FileText,
  Mail,
  Link2,
  Gauge,
  Code2,
  HeartHandshake,
  Building2,
  GraduationCap,
  FolderGit2,
  BadgeCheck,
  Trophy,
  BookOpen,
  Languages,
  Sparkles,
  Users,
  FileStack,
  type LucideIcon,
} from "lucide-react";
import type { SectionType } from "./types";

export const SECTION_ICONS: Record<SectionType, LucideIcon> = {
  name: User,
  photo: ImageIcon,
  title: Briefcase,
  summary: FileText,
  contact: Mail,
  social: Link2,
  skills: Gauge,
  technicalSkills: Code2,
  softSkills: HeartHandshake,
  experience: Building2,
  education: GraduationCap,
  projects: FolderGit2,
  certifications: BadgeCheck,
  awards: Trophy,
  publications: BookOpen,
  languages: Languages,
  interests: Sparkles,
  references: Users,
  custom: FileStack,
};
