import type { Book } from "./types";

// Metadata and original summaries only — no hosted copyrighted content.
export const BOOKS: Book[] = [
  {
    id: "book-lessons-learned",
    title: "Lessons Learned in Software Testing",
    author: "Cem Kaner, James Bach, Bret Pettichord",
    publisher: "Wiley",
    edition: "1st Edition",
    category: "Manual Testing",
    accentColor: "#2563eb",
    difficulty: "Intermediate",
    summary: "A collection of 293 concise, hard-won lessons on testing practice, management, and mindset — less a textbook and more a distilled set of field notes from three of the field's most respected practitioners.",
    keyLearnings: [
      "Testing is a skilled, investigative discipline, not a checklist-following task.",
      "Context matters more than any single 'best practice.'",
      "How to think critically about metrics, coverage claims, and test documentation.",
    ],
  },
  {
    id: "book-agile-testing",
    title: "Agile Testing: A Practical Guide for Testers and Agile Teams",
    author: "Lisa Crispin, Janet Gregory",
    publisher: "Addison-Wesley",
    edition: "1st Edition",
    category: "Manual Testing",
    accentColor: "#16a34a",
    difficulty: "Beginner",
    summary: "The definitive guide to how testing actually works inside Agile teams — whole-team quality ownership, the Agile Testing Quadrants, and practical guidance for testers moving from Waterfall to Scrum/Kanban.",
    keyLearnings: [
      "The Agile Testing Quadrants model for categorizing test types by purpose.",
      "How testers collaborate with the whole team instead of testing in a separate phase.",
      "Balancing automated regression safety nets with exploratory testing.",
    ],
  },
  {
    id: "book-explore-it",
    title: "Explore It! Reduce Risk and Increase Confidence with Exploratory Testing",
    author: "Elisabeth Hendrickson",
    publisher: "Pragmatic Bookshelf",
    edition: "1st Edition",
    category: "Manual Testing",
    accentColor: "#7c3aed",
    difficulty: "Beginner",
    summary: "A short, practical guide to exploratory testing as a structured skill — test charters, tours, and heuristics for finding the bugs a scripted test suite never would.",
    keyLearnings: ["How to write test charters that stay focused without being rigid.", "Tour-based heuristics (e.g. the 'money tour', 'landmark tour') for exploring an unfamiliar app.", "How exploratory testing complements, rather than replaces, scripted testing."],
  },
  {
    id: "book-clean-coder",
    title: "The Clean Coder: A Code of Conduct for Professional Programmers",
    author: "Robert C. Martin",
    publisher: "Prentice Hall",
    edition: "1st Edition",
    category: "Programming",
    accentColor: "#dc2626",
    difficulty: "Intermediate",
    summary: "Less about syntax and more about professionalism — estimating honestly, saying no responsibly, and treating testing (including TDD) as a core professional discipline rather than an afterthought.",
    keyLearnings: ["Why professional developers treat automated tests as a first-class deliverable.", "How to give and negotiate estimates honestly under pressure.", "The discipline of test-driven development as a design tool, not just a safety net."],
  },
  {
    id: "book-eloquent-js",
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    publisher: "No Starch Press",
    edition: "4th Edition",
    category: "Programming",
    accentColor: "#f59e0b",
    difficulty: "Beginner",
    summary: "A free, thorough, project-based introduction to JavaScript — the language most test automation frameworks (Playwright, Cypress) are built on.",
    keyLearnings: ["Core JS fundamentals: functions, closures, async/await, and the DOM.", "How to reason about asynchronous code, essential for writing reliable automated tests.", "Enough depth to comfortably read and extend an existing automation framework."],
  },
  {
    id: "book-sql-antipatterns",
    title: "SQL Antipatterns: Avoiding the Pitfalls of Database Programming",
    author: "Bill Karwin",
    publisher: "Pragmatic Bookshelf",
    edition: "1st Edition",
    category: "SQL",
    accentColor: "#0891b2",
    difficulty: "Intermediate",
    summary: "A tour of the most common database design and query mistakes, framed as 'antipatterns' — genuinely useful for testers who need to validate data integrity, not just write SELECTs.",
    keyLearnings: ["Common schema design mistakes that cause subtle data-integrity bugs.", "Why 'it returns the right row' isn't the same as 'the schema is correct.'", "Practical query patterns for validating joins, constraints, and normalization."],
  },
  {
    id: "book-rest-api-design",
    title: "REST API Design Rulebook",
    author: "Mark Masse",
    publisher: "O'Reilly Media",
    edition: "1st Edition",
    category: "API",
    accentColor: "#9333ea",
    difficulty: "Intermediate",
    summary: "A compact rulebook for what a well-designed REST API should look like — essential background for API testers, since knowing what 'correct' looks like is half of testing it.",
    keyLearnings: ["Resource naming, HTTP verb usage, and status code conventions.", "How to evaluate whether an API's design is internally consistent.", "A vocabulary for writing precise API bug reports (e.g. 'this violates REST resource-naming conventions')."],
  },
  {
    id: "book-phoenix-project",
    title: "The Phoenix Project",
    author: "Gene Kim, Kevin Behr, George Spafford",
    publisher: "IT Revolution Press",
    edition: "5th Anniversary Edition",
    category: "DevOps",
    accentColor: "#ea580c",
    difficulty: "Beginner",
    summary: "A business novel that dramatizes what DevOps actually solves — the chaos of manual deployments, unmanaged work-in-progress, and testing bolted on at the very end of a broken pipeline.",
    keyLearnings: ["Why continuous testing and deployment reduce risk instead of increasing it.", "The 'Three Ways' of DevOps: flow, feedback, and continuous learning.", "How QA bottlenecks often trace back to process problems, not testing effort."],
  },
  {
    id: "book-ml-testing",
    title: "Machine Learning Design Patterns",
    author: "Valliappa Lakshmanan, Sara Robinson, Michael Munn",
    publisher: "O'Reilly Media",
    edition: "1st Edition",
    category: "AI Testing",
    accentColor: "#0d9488",
    difficulty: "Advanced",
    summary: "Not a testing book specifically, but the most practical reference for understanding how ML/AI systems are actually built — necessary context before you can meaningfully test model behavior, drift, and evaluation pipelines.",
    keyLearnings: ["Common patterns in model training, serving, and evaluation pipelines.", "Where non-determinism enters an ML system, and why that changes how you test it.", "Vocabulary for reasoning about model quality beyond a single accuracy number."],
  },
];

export function getBooksByCategory(category: string): Book[] {
  return BOOKS.filter((b) => b.category === category);
}
