import type { InterviewQuestion } from "./types";

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  // ---- Fresher ----
  { id: "iq-fresher-1", level: "fresher", category: "technical", question: "What is software testing and why is it important?", modelAnswer: "Software testing is the process of evaluating a system to find defects and verify it meets requirements. It's important because it catches problems before customers do, reduces the cost of fixing defects (cheaper the earlier they're found), and gives objective evidence for release decisions.", tags: ["fundamentals"] },
  { id: "iq-fresher-2", level: "fresher", category: "technical", question: "Can testing guarantee a bug-free product? Why or why not?", modelAnswer: "No. Testing shows the presence of defects, not their absence (one of the seven testing principles). Exhaustive testing of every input/path combination is practically impossible, so testing reduces risk to an acceptable level rather than eliminating it entirely.", tags: ["fundamentals", "principles"] },
  { id: "iq-fresher-3", level: "fresher", category: "technical", question: "What's the difference between Waterfall and Agile?", modelAnswer: "Waterfall is sequential — each SDLC stage (requirements, design, coding, testing) happens once, in order, with testing at the end. Agile is iterative — all stages repeat in short sprints, shipping working, tested software every 1-4 weeks, which surfaces defects and misunderstandings earlier.", tags: ["sdlc"] },
  { id: "iq-fresher-4", level: "fresher", category: "technical", question: "Walk me through the phases of STLC.", modelAnswer: "Requirement Analysis → Test Planning → Test Case Development → Environment Setup → Test Execution → Test Closure. Each phase has entry and exit criteria to make sure nothing is skipped.", tags: ["stlc"] },
  { id: "iq-fresher-5", level: "fresher", category: "technical", question: "What is the 'pesticide paradox' in testing?", modelAnswer: "Running the exact same test cases repeatedly eventually stops finding new defects, the same way pests build resistance to a repeated pesticide. Test suites need to be reviewed and updated with new cases over time.", tags: ["principles"] },
  { id: "iq-fresher-6", level: "fresher", category: "technical", question: "Explain verification vs validation with an example.", modelAnswer: "Verification checks a work product against its spec — e.g. reviewing a design document. Validation checks the finished product against real user needs — e.g. running UAT. Code can pass verification (matches the spec) and still fail validation (the spec described the wrong feature).", tags: ["verification", "validation"] },
  { id: "iq-fresher-7", level: "fresher", category: "technical", question: "What is the difference between QA and QC?", modelAnswer: "QA is process-focused and preventive — improving how the team works so fewer defects get introduced. QC is product-focused and detective — inspecting the actual deliverable. Testing is the main QC technique.", tags: ["qa", "qc"] },
  { id: "iq-fresher-8", level: "fresher", category: "technical", question: "Describe the defect life cycle.", modelAnswer: "New → Assigned → Open → Fixed → Retest → Verified → Closed, with branch states like Reopened (fix didn't work), Rejected (not actually a bug), Duplicate, and Deferred.", tags: ["defects"] },
  { id: "iq-fresher-9", level: "fresher", category: "scenario", question: "A developer says a bug you logged 'works fine on my machine.' What do you do?", modelAnswer: "Confirm the exact environment (OS, browser/version, build number, test data) you used versus theirs. Attach screenshots/screen recordings and precise repro steps. If it's still not reproducible on their side, pair up and reproduce it live together rather than arguing over chat.", tags: ["defects", "communication"] },
  { id: "iq-fresher-10", level: "fresher", category: "technical", question: "What's the difference between severity and priority?", modelAnswer: "Severity is the technical impact of a defect (set by the tester). Priority is the business urgency of fixing it (usually set by the lead/product owner). They're independent — a typo on the homepage can be low severity but high priority.", tags: ["defects"] },
  { id: "iq-fresher-11", level: "fresher", category: "technical", question: "When would you run a smoke test vs a sanity test vs a regression test?", modelAnswer: "Smoke test: right after a new build, to check it's stable enough to test further. Sanity test: after a specific small fix, to quickly confirm just that area works. Regression test: before a release, to catch unintended side effects across the wider system.", tags: ["smoke", "sanity", "regression"] },
  { id: "iq-fresher-12", level: "fresher", category: "technical", question: "What's the difference between black box and white box testing?", modelAnswer: "Black box testing works from inputs/outputs only, with no code knowledge — typical of manual functional testing. White box testing examines internal code structure directly (statement/branch/path coverage) — typical of developer unit testing.", tags: ["black-box", "white-box"] },
  { id: "iq-fresher-13", level: "fresher", category: "scenario", question: "You have one day left before release and found a critical bug. What do you do?", modelAnswer: "Log it immediately with full details and severity/priority, notify the lead/PM right away rather than waiting for a standup, and help assess impact and workarounds. The decision to delay or ship-with-a-known-issue is a team/business call, not something to sit on.", tags: ["scenario", "prioritization"] },
  { id: "iq-fresher-14", level: "fresher", category: "hr", question: "Why do you want to work in QA/testing?", modelAnswer: "A good answer is specific and honest: mentions genuine interest in problem-solving, attention to detail, enjoying the investigative/analytical side of understanding how systems break, and impact — protecting real users from bad experiences. Avoid generic answers like 'I like computers.'", tags: ["hr"] },
  { id: "iq-fresher-15", level: "fresher", category: "hr", question: "Tell me about a time you found a significant bug. What did you do?", modelAnswer: "Use a structure like STAR (Situation, Task, Action, Result): describe the context, what you were testing, exactly how you found it (steps, tools), and the outcome (was it fixed before release, what impact did catching it have).", tags: ["hr", "star-method"] },
  { id: "iq-fresher-16", level: "fresher", category: "sql", question: "Write a SQL query to find duplicate emails in a `users` table.", modelAnswer: "SELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1; — groups rows by email and keeps only groups appearing more than once.", tags: ["sql"] },
  { id: "iq-fresher-17", level: "fresher", category: "sql", question: "What's the difference between INNER JOIN and LEFT JOIN?", modelAnswer: "INNER JOIN returns only rows with matches in both tables. LEFT JOIN returns all rows from the left table, with NULLs filled in for any columns from the right table where there's no match.", tags: ["sql", "joins"] },
  { id: "iq-fresher-18", level: "fresher", category: "api", question: "What's the difference between PUT and PATCH?", modelAnswer: "PUT replaces the entire resource with the payload provided. PATCH applies a partial update, changing only the fields included in the request.", tags: ["api", "http"] },
  { id: "iq-fresher-19", level: "fresher", category: "api", question: "What does a 404 vs a 500 status code mean?", modelAnswer: "404 Not Found means the requested resource doesn't exist at that URL — a client-side addressing issue. 500 Internal Server Error means the server encountered an unexpected condition while processing a valid request — a server-side failure.", tags: ["api", "http-status"] },
  { id: "iq-fresher-20", level: "fresher", category: "coding", question: "How would you test a function that calculates a discount, given a price and a percentage?", modelAnswer: "Use equivalence partitioning and boundary values: 0% and 100% discount, negative price (invalid input), price of 0, a normal mid-range case, non-numeric input, and a percentage over 100 (invalid). Check both the return value and that no exception is thrown for invalid input unless that's the documented behavior.", tags: ["test-design", "boundary-values"] },

  // ---- 1-2 Years ----
  { id: "iq-junior-1", level: "1-2y", category: "technical", question: "What is equivalence partitioning and why does it matter?", modelAnswer: "It's a test design technique that divides input data into partitions expected to behave the same way, so you only need to test one representative value per partition instead of every possible value — dramatically reducing the number of test cases needed while keeping coverage meaningful.", tags: ["test-design"] },
  { id: "iq-junior-2", level: "1-2y", category: "technical", question: "What's boundary value analysis and how does it relate to equivalence partitioning?", modelAnswer: "Boundary value analysis tests the edges of equivalence partitions (just inside, on, and just outside a boundary) because defects cluster at boundaries far more often than in the middle of a range. It's used alongside equivalence partitioning, not instead of it.", tags: ["test-design"] },
  { id: "iq-junior-3", level: "1-2y", category: "scenario", question: "How do you decide what to automate vs keep manual?", modelAnswer: "Automate high-value, repetitive, stable tests (smoke, regression, data-driven cases) with a good ROI over many runs. Keep exploratory, usability, and frequently-changing-UI tests manual, since automation maintenance cost would outweigh the benefit.", tags: ["automation-strategy"] },
  { id: "iq-junior-4", level: "1-2y", category: "playwright", question: "How does Playwright's auto-waiting work, and why does it reduce flaky tests?", modelAnswer: "Playwright automatically waits for an element to be actionable (visible, stable, enabled, receiving events) before interacting with it, instead of requiring explicit sleeps. This removes a huge source of flakiness caused by fixed waits that are either too short (race conditions) or too long (slow suites).", tags: ["playwright"] },
  { id: "iq-junior-5", level: "1-2y", category: "selenium", question: "What's the difference between implicit and explicit waits in Selenium?", modelAnswer: "An implicit wait applies globally to every element lookup, polling for a fixed timeout before throwing NoSuchElementException. An explicit wait (WebDriverWait + ExpectedConditions) targets a specific condition on a specific element, and is generally preferred for precision and readability.", tags: ["selenium"] },
  { id: "iq-junior-6", level: "1-2y", category: "sql", question: "Write a query to find the second-highest salary from an `employees` table.", modelAnswer: "SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees); — or use DENSE_RANK() OVER (ORDER BY salary DESC) and filter rank = 2 for a version that handles ties correctly.", tags: ["sql"] },
  { id: "iq-junior-7", level: "1-2y", category: "scenario", question: "A regression suite that used to take 20 minutes now takes 2 hours. What do you investigate?", modelAnswer: "Check for newly added tests bloating the suite unnecessarily, unstable waits/retries masking flaky tests, environment/infra slowdowns, and whether tests can run in parallel instead of serially. Profile the suite to find the actual slowest tests rather than guessing.", tags: ["automation", "performance"] },
  { id: "iq-junior-8", level: "1-2y", category: "api", question: "How would you test API authentication and authorization?", modelAnswer: "Authentication: test valid credentials succeed, invalid/expired tokens are rejected with 401, and missing tokens are rejected. Authorization: test that a valid user can only access resources they're permitted to (403 for others), including horizontal privilege checks (user A can't see user B's data) and vertical privilege checks (regular user can't hit admin-only endpoints).", tags: ["api", "security"] },

  // ---- SDET ----
  { id: "iq-sdet-1", level: "sdet", category: "technical", question: "How do you design a test automation framework from scratch?", modelAnswer: "Start with the layers: a driver/config layer (browser/API clients, environment config), a page-object or component-object layer (locators + actions), a test-data layer (fixtures/builders, isolated per test), and the test layer itself (assertions, no logic duplication). Add reporting, retries for genuine flakiness only, and CI integration last, once the core is stable.", tags: ["framework-design"] },
  { id: "iq-sdet-2", level: "sdet", category: "technical", question: "How do you keep a large automation suite from becoming flaky over time?", modelAnswer: "Enforce proper waits (no fixed sleeps), isolate test data per test (no shared mutable state), run tests in parallel to surface hidden ordering dependencies early, track flaky tests with a quarantine process instead of ignoring them, and review/retire stale tests regularly (the pesticide paradox applies to automation too).", tags: ["automation", "flakiness"] },
  { id: "iq-sdet-3", level: "sdet", category: "coding", question: "How would you implement a retry mechanism for a genuinely flaky network call in a test, without masking real bugs?", modelAnswer: "Retry only on specific, known-transient failure types (timeouts, 5xx from a flaky test environment) with a small fixed retry count and backoff, and log every retry so it's visible in reports. Never blanket-retry on assertion failures — that hides real regressions instead of fixing the underlying instability.", tags: ["automation", "flakiness"] },
  { id: "iq-sdet-4", level: "sdet", category: "technical", question: "What's your strategy for data-driven testing at scale?", modelAnswer: "Separate test logic from test data completely — data lives in fixtures/CSV/JSON, the test iterates over it. Use builders/factories for generating valid-by-default objects that individual tests can override just the field(s) under test, rather than hand-writing full objects everywhere.", tags: ["data-driven"] },
  { id: "iq-sdet-5", level: "sdet", category: "scenario", question: "CI pipeline test time has grown from 10 minutes to 45 minutes as the suite grew. How do you fix it without cutting coverage?", modelAnswer: "Parallelize across workers/shards, split unit/API tests (fast) from UI/E2E tests (slow) into separate pipeline stages so fast feedback isn't blocked by slow tests, cache dependencies/build artifacts, and audit for redundant coverage (multiple tests exercising the same path) before removing anything meaningful.", tags: ["ci-cd", "performance"] },
];
