import type { Product } from "./types";

/**
 * Static, deterministic catalog — never faker-generated — so bugs tied to
 * specific SKUs (price mismatch, out-of-stock, rating rounding) are
 * reproducible every time.
 */
export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Wireless Mouse",
    category: "Electronics",
    price: 24.99, // charged at checkout — deliberately different from listPrice (BUG-012)
    listPrice: 19.99,
    rating: 4.45,
    stock: 40,
    description: "A reliable 2.4GHz wireless mouse with adjustable DPI.",
    emoji: "🖱️",
  },
  {
    id: "p2",
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 59.99,
    listPrice: 59.99,
    rating: 4.7,
    stock: 25,
    description: "Tactile mechanical keyboard with RGB backlighting.",
    emoji: "⌨️",
  },
  {
    id: "p3",
    name: "USB-C Hub",
    category: "Electronics",
    price: 24.99,
    listPrice: 24.99,
    rating: 4.2,
    stock: 0, // deliberately out of stock (BUG-008)
    description: "7-in-1 USB-C hub with HDMI and SD card slots.",
    emoji: "🔌",
  },
  {
    id: "p4",
    name: "Noise Cancelling Headphones",
    category: "Electronics",
    price: 89.99,
    listPrice: 89.99,
    rating: 4.6,
    stock: 15,
    description: "Over-ear headphones with active noise cancellation.",
    emoji: "🎧",
  },
  {
    id: "p5",
    name: "Portable SSD 1TB",
    category: "Electronics",
    price: 74.99,
    listPrice: 74.99,
    rating: 4.8,
    stock: 30,
    description: "Compact 1TB external SSD with USB 3.2 transfer speeds.",
    emoji: "💾",
  },
  {
    id: "p6",
    name: "Smart Watch",
    category: "Electronics",
    price: 129.99,
    listPrice: 129.99,
    rating: 4.3,
    stock: 12,
    description: "Fitness tracking smart watch with heart-rate monitor.",
    emoji: "⌚",
  },
  {
    id: "p7",
    name: "Yoga Mat",
    category: "Sports",
    price: 22.5,
    listPrice: 22.5,
    rating: 4.5,
    stock: 50,
    description: "Non-slip 6mm yoga mat with carry strap.",
    emoji: "🧘",
  },
  {
    id: "p8",
    name: "Running Shoes",
    category: "Sports",
    price: 64.99,
    listPrice: 64.99,
    rating: 4.4,
    stock: 20,
    description: "Lightweight running shoes with breathable mesh upper.",
    emoji: "👟",
  },
  {
    id: "p9",
    name: "Dumbbell Set 20kg",
    category: "Sports",
    price: 45.0,
    listPrice: 45.0,
    rating: 4.6,
    stock: 18,
    description: "Adjustable dumbbell set, 20kg total, rubber coated.",
    emoji: "🏋️",
  },
  {
    id: "p10",
    name: "Water Bottle 1L",
    category: "Sports",
    price: 12.99,
    listPrice: 12.99,
    rating: 4.1,
    stock: 100,
    description: "Insulated stainless steel water bottle, 1 litre.",
    emoji: "🚰",
  },
  {
    id: "p11",
    name: "Cotton T-Shirt",
    category: "Fashion",
    price: 14.99,
    listPrice: 14.99,
    rating: 4.0,
    stock: 60,
    description: "Classic fit 100% cotton crew neck t-shirt.",
    emoji: "👕",
  },
  {
    id: "p12",
    name: "Denim Jacket",
    category: "Fashion",
    price: 49.99,
    listPrice: 49.99,
    rating: 4.3,
    stock: 22,
    description: "Classic denim jacket with button front.",
    emoji: "🧥",
  },
  {
    id: "p13",
    name: "Leather Wallet",
    category: "Fashion",
    price: 27.5,
    listPrice: 27.5,
    rating: 4.5,
    stock: 35,
    description: "Slim bifold leather wallet with card slots.",
    emoji: "👛",
  },
  {
    id: "p14",
    name: "Sunglasses",
    category: "Fashion",
    price: 18.0,
    listPrice: 18.0,
    rating: 3.9,
    stock: 40,
    description: "UV400 polarized sunglasses, unisex frame.",
    emoji: "🕶️",
  },
  {
    id: "p15",
    name: "Ceramic Mug Set",
    category: "Home",
    price: 16.99,
    listPrice: 16.99,
    rating: 4.2,
    stock: 45,
    description: "Set of 4 ceramic mugs, 350ml each.",
    emoji: "☕",
  },
  {
    id: "p16",
    name: "Non-Stick Pan",
    category: "Home",
    price: 32.0,
    listPrice: 32.0,
    rating: 4.4,
    stock: 28,
    description: "28cm non-stick frying pan with heat-resistant handle.",
    emoji: "🍳",
  },
  {
    id: "p17",
    name: "LED Desk Lamp",
    category: "Home",
    price: 21.99,
    listPrice: 21.99,
    rating: 4.3,
    stock: 33,
    description: "Dimmable LED desk lamp with USB charging port.",
    emoji: "💡",
  },
  {
    id: "p18",
    name: "Memory Foam Pillow",
    category: "Home",
    price: 29.99,
    listPrice: 29.99,
    rating: 4.6,
    stock: 26,
    description: "Contoured memory foam pillow for neck support.",
    emoji: "🛏️",
  },
  {
    id: "p19",
    name: "The Pragmatic Tester",
    category: "Books",
    price: 24.0,
    listPrice: 24.0,
    rating: 4.9,
    stock: 50,
    description: "A field guide to practical software testing.",
    emoji: "📘",
  },
  {
    id: "p20",
    name: "Clean Code",
    category: "Books",
    price: 28.0,
    listPrice: 28.0,
    rating: 4.85,
    stock: 42,
    description: "A handbook of agile software craftsmanship.",
    emoji: "📗",
  },
  {
    id: "p21",
    name: "Atomic Habits",
    category: "Books",
    price: 15.99,
    listPrice: 15.99,
    rating: 4.9,
    stock: 70,
    description: "An easy and proven way to build good habits.",
    emoji: "📙",
  },
  {
    id: "p22",
    name: "Face Moisturizer",
    category: "Beauty",
    price: 13.5,
    listPrice: 13.5,
    rating: 4.2,
    stock: 55,
    description: "Lightweight daily moisturizer for all skin types.",
    emoji: "🧴",
  },
  {
    id: "p23",
    name: "Vitamin C Serum",
    category: "Beauty",
    price: 17.99,
    listPrice: 17.99,
    rating: 4.4,
    stock: 38,
    description: "Brightening vitamin C serum, 30ml dropper bottle.",
    emoji: "💧",
  },
  {
    id: "p24",
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 39.99,
    listPrice: 39.99,
    rating: 4.5,
    stock: 24,
    description: "Portable Bluetooth speaker with 12-hour battery life.",
    emoji: "🔊",
  },
];

export const CATEGORIES = Array.from(new Set(PRODUCTS.map((p) => p.category))).sort();

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
