export const profile = {
  name: 'Antony Joshua S',
  role: 'Quality Analyst',
  tagline: '3+ years building defect-free software across web, mobile, VR, and AI platforms.',
  location: 'Chennai, India',
  email: 'antonyjoshua413@gmail.com',
  phone: '+91 95140 84222',
  github: 'https://github.com/Antonyjoshua',
  linkedin: 'https://linkedin.com/in/antony-joshua-471704aj',
  resumeUrl: '/resume.pdf',
};

export const roles = [
  'AI Quality Engineer',
  'Automation Engineer',
  'Playwright Specialist',
  'AI Testing Expert',
  'Bug Hunter 🐛',
  'Problem Solver',
];

export const stats = [
  { value: 2500, suffix: '+', label: 'Defects Found',      icon: '🐛' },
  { value: 3,    suffix: '+', label: 'Years Experience',   icon: '⚡' },
  { value: 9,    suffix: '+', label: 'Projects Delivered', icon: '🚀' },
  { value: 8,    suffix: '',  label: 'Domains Covered',    icon: '🌐' },
];

export const experience = [
  {
    company:   'Scope Thinkers',
    role:      'Quality Analyst',
    period:    'Dec 2025 – Present',
    current:   true,
    mission:   'MISSION ACTIVE',
    color:     '#00d4ff',
    highlights: [
      'Performing manual and automation testing across EdTech and Entertainment domains.',
      'Building end-to-end automation test suites using Playwright with TypeScript.',
      'Tested web, Android, and iOS platforms for Jeshwar Teaching — live streaming & e-learning.',
      'Validated point purchase/redemption, franchise management, and loyalty workflows for Funtown.',
    ],
    tech: ['Playwright', 'TypeScript', 'Manual Testing', 'Android', 'iOS', 'Agile'],
  },
  {
    company:   'NITInnov Technologies Pvt Ltd',
    role:      'Software Tester',
    period:    'Jun 2024 – Sep 2025',
    current:   false,
    mission:   'MISSION COMPLETE',
    color:     '#a855f7',
    highlights: [
      'Manual testing on VR-based healthcare platform (ConfidentoAI) across VR, web, and mobile.',
      'Validated Muse EEG device integration, ensuring accurate data capture within the app.',
      'Tested RAG and machine learning models; designed and validated prompt templates.',
      'Executed detailed manual test cases, tracking defects in Agile sprints via JIRA.',
    ],
    tech: ['VR Testing', 'Mobile Testing', 'EEG Validation', 'ML Model Testing', 'Agile'],
  },
  {
    company:   'Arkashya Tech Solution Pvt Ltd',
    role:      'Software Tester',
    period:    'Jul 2023 – May 2024',
    current:   false,
    mission:   'MISSION COMPLETE',
    color:     '#00ff88',
    highlights: [
      'Designed and executed automation test scripts using Selenium + TestNG.',
      'Conducted manual test cases for functional and regression testing.',
      'Prepared detailed bug reports and assisted developers with root cause analysis.',
      'Collaborated with product owners and stakeholders in Agile sprints.',
    ],
    tech: ['Selenium', 'TestNG', 'Regression Testing', 'Bug Reporting'],
  },
  {
    company:   'Arkashya Tech Solution Pvt Ltd',
    role:      'Software Tester — Intern',
    period:    'Mar 2023 – Jun 2023',
    current:   false,
    mission:   'MISSION COMPLETE',
    color:     '#ff2d78',
    highlights: [
      'Assisted in manual testing of web and mobile applications.',
      'Created and executed basic test cases; logged and tracked defects.',
      'Gained exposure to SDLC, STLC, and defect life cycle processes.',
      'Developed introductory Selenium automation scripts.',
    ],
    tech: ['Manual Testing', 'SDLC', 'STLC', 'Selenium'],
  },
  {
    company:   'Sutherland Global Services',
    role:      'Technical Support — SME',
    period:    'Oct 2020 – Oct 2022',
    current:   false,
    mission:   'MISSION COMPLETE',
    color:     '#f97316',
    highlights: [
      'Delivered technical support to Amazon customers via phone, email, and chat.',
      'Part of core launch team supporting a wide range of Amazon.com products.',
      'Promoted to Team Lead for 10 months, managing operations and mentoring members.',
      'Recognised with 2× RnR Awards for consistent performance and service excellence.',
    ],
    tech: ['Team Lead', 'Technical Support', 'Amazon', '2× RnR Award'],
  },
];

export const projects = [
  {
    title:       'Jeshwar Teaching',
    subtitle:    'EdTech · Live Streaming Platform',
    company:     'Scope Thinkers',
    description: 'Full-stack EdTech platform — live classes, video streaming, digital content, online bookstore. Validated Web, Android, and iOS applications across all sub-domains.',
    tags:        ['Playwright', 'TypeScript', 'Live Streaming', 'iOS', 'Android'],
    gradient:    'from-violet-600 to-purple-900',
    color:       '#7c3aed',
    icon:        '📚',
    status:      'enterprise',
  },
  {
    title:       'Funtown Kids Park',
    subtitle:    'Entertainment · Recreation Management',
    company:     'Scope Thinkers',
    description: 'Amusement park management platform — point purchase & redemption, play activity management, franchise management, loyalty & rewards. Tested Android app and web portal.',
    tags:        ['Playwright', 'TypeScript', 'Android', 'Loyalty Systems'],
    gradient:    'from-cyan-600 to-blue-900',
    color:       '#0891b2',
    icon:        '🎡',
    status:      'enterprise',
  },
  {
    title:       'Scope AI Chat',
    subtitle:    'Generative AI · RAG Architecture',
    company:     'Scope Thinkers',
    description: 'Domain-specific AI chatbot on RAG architecture. Validated context-aware responses, multi-source data ingestion, document processing pipelines, and widget integration.',
    tags:        ['RAG', 'Generative AI', 'Playwright', 'TypeScript', 'SaaS'],
    gradient:    'from-orange-600 to-red-900',
    color:       '#ea580c',
    icon:        '🤖',
    status:      'live',
  },
  {
    title:       'ConfidentoAI',
    subtitle:    'Healthcare · VR Platform',
    company:     'NITInnov Technologies',
    description: 'VR-based healthcare solution — manual testing across web, mobile, and VR. Validated Muse EEG integration, tested RAG and ML models, managed defects in Agile sprints.',
    tags:        ['VR', 'EEG', 'ML Testing', 'RAG', 'iOS', 'Android'],
    gradient:    'from-blue-600 to-indigo-900',
    color:       '#2563eb',
    icon:        '🥽',
    status:      'enterprise',
  },
  {
    title:       'Scope Employee Portal',
    subtitle:    'HRMS · Human Resource Management',
    company:     'Scope Thinkers',
    description: 'HRMS platform covering employee information management, attendance tracking, leave management, and HR operational workflows across web and mobile.',
    tags:        ['Playwright', 'TypeScript', 'Mobile', 'Web', 'HR Automation'],
    gradient:    'from-emerald-600 to-teal-900',
    color:       '#059669',
    icon:        '🏢',
    status:      'enterprise',
  },
  {
    title:       'MyHotel AI',
    subtitle:    'Hospitality · Property Management',
    company:     'Arkashya Tech Solution',
    description: 'Functional, regression, and UI testing on web, Android, and iOS. Executed automation scripts using Selenium + TestNG across all key PMS modules.',
    tags:        ['Selenium', 'TestNG', 'iOS', 'Android', 'UI Testing'],
    gradient:    'from-pink-600 to-rose-900',
    color:       '#db2777',
    icon:        '🏨',
    status:      'enterprise',
  },
  {
    title:       'Cornovus Capital',
    subtitle:    'Finance · Real Estate Loans',
    company:     'NITInnov Technologies',
    description: 'Functional and regression testing for commercial real estate loan workflows. Validated loan calculations for equity, term length, and interest rates.',
    tags:        ['Functional Testing', 'Regression', 'Finance', 'Web'],
    gradient:    'from-amber-600 to-orange-900',
    color:       '#ca8a04',
    icon:        '🏦',
    status:      'enterprise',
  },
  {
    title:       'ACW Card',
    subtitle:    'NFC Technology · Digital Business',
    company:     'Arkashya Tech Solution',
    description: 'Cross-device NFC testing for a smart digital business card application. Validated interactions and compatibility across devices.',
    tags:        ['NFC Testing', 'Cross-device', 'Compatibility'],
    gradient:    'from-slate-600 to-gray-900',
    color:       '#475569',
    icon:        '📇',
    status:      'live',
  },
];

export const skills = [
  { name: 'Playwright',         level: 95, color: '#00d4ff', category: 'Automation' },
  { name: 'Selenium',           level: 88, color: '#a855f7', category: 'Automation' },
  { name: 'TypeScript',         level: 85, color: '#3178c6', category: 'Programming' },
  { name: 'JavaScript',         level: 80, color: '#f7df1e', category: 'Programming' },
  { name: 'AI / RAG Testing',   level: 90, color: '#00ff88', category: 'AI Testing' },
  { name: 'ML Model Testing',   level: 82, color: '#ff2d78', category: 'AI Testing' },
  { name: 'API Testing',        level: 88, color: '#f97316', category: 'Testing' },
  { name: 'VR Testing',         level: 78, color: '#818cf8', category: 'Testing' },
  { name: 'Manual Testing',     level: 95, color: '#34d399', category: 'Testing' },
  { name: 'JIRA',               level: 92, color: '#0052cc', category: 'Tools' },
  { name: 'Azure DevOps',       level: 75, color: '#0078d4', category: 'Tools' },
  { name: 'Jenkins',            level: 72, color: '#d24939', category: 'CI/CD' },
];

export const certifications = [
  {
    title:    'Selenium WebDriver with Java',
    subtitle: 'Basics to Advanced + Frameworks',
    issuer:   'Udemy',
    date:     'Oct 2024',
    instructor: 'Rahul Shetty',
    duration: '55.5 hrs',
    tags:     ['Selenium', 'Java', 'TestNG', 'Frameworks'],
    color:    '#7c3aed',
    badge:    '🏆',
  },
  {
    title:    'ML (AI) Testing',
    subtitle: 'Introduction to Machine Learning Models Testing',
    issuer:   'Udemy',
    date:     'Dec 2024',
    instructor: 'Rahul Shetty',
    duration: '5 hrs',
    tags:     ['AI Testing', 'ML Models', 'QA Strategy'],
    color:    '#00d4ff',
    badge:    '🤖',
  },
  {
    title:    'Master Class — QA Professionals',
    subtitle: 'Certificate of Participation',
    issuer:   'Testleaf',
    date:     'Oct 2025',
    instructor: 'Testleaf',
    duration: '',
    tags:     ['QA Best Practices', 'Test Strategy'],
    color:    '#a855f7',
    badge:    '⚡',
  },
  {
    title:    'Automation Testing Skills',
    subtitle: 'Cracking QA Roles in Top Tech Companies',
    issuer:   'GUVI × HCL',
    date:     'Nov 2025',
    instructor: 'GUVI | HCL',
    duration: '',
    tags:     ['Automation', 'Interview Prep', 'Career Growth'],
    color:    '#00ff88',
    badge:    '🚀',
  },
];

export const aiLab = [
  { icon: '🕹️', title: 'AI Agents',          desc: 'Autonomous testing agents that plan, execute, and report test scenarios without human intervention.', tag: 'Live', color: '#00d4ff' },
  { icon: '🔌', title: 'MCP Integration',     desc: 'Model Context Protocol adapters for real-time AI access to test results, logs, and CI/CD state.',   tag: 'In Progress', color: '#a855f7' },
  { icon: '📝', title: 'Prompt Engineering',  desc: 'Prompts that reliably extract bug reproduction steps, severity, and fix suggestions from raw logs.',  tag: 'Live', color: '#00ff88' },
  { icon: '🧠', title: 'Smart Test Selection', desc: 'ML-based test prioritization predicting which cases will catch regressions for a given code change.', tag: 'Research', color: '#ff2d78' },
  { icon: '⚖️', title: 'LLM Validation',      desc: 'Frameworks for evaluating LLM accuracy, hallucination rate, and relevance in production RAG systems.', tag: 'Live', color: '#f97316' },
  { icon: '♾️', title: 'Autonomous QA',        desc: 'Self-healing test suite that detects flaky tests, auto-retries with strategies, and reports intelligently.', tag: 'In Progress', color: '#818cf8' },
];
