import type { Challenge } from "./types";

const XP = { Beginner: 10, Intermediate: 20, Advanced: 35, Expert: 50 } as const;

export const CHALLENGES: Challenge[] = [
  // ─── Boundary Value Analysis ────────────────────────────────────────────
  {
    id: "bva-age",
    mechanic: "bva",
    title: "Age Eligibility Boundaries",
    technique: "Boundary Value Analysis",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "A Brightbasket promotion is open to shoppers aged 18 to 60 (inclusive). List the boundary values you would test.",
    fieldLabel: "Age (years)",
    min: 18,
    max: 60,
    hints: [
      "Boundary Value Analysis tests the edges of a valid range, not just the middle.",
      "For a range of min–max, test min-1, min, min+1, max-1, max, and max+1.",
      "For 18–60 that's: 17, 18, 19, 59, 60, 61.",
    ],
    explanation: "The classic BVA set for an inclusive range [min, max] is {min-1, min, min+1, max-1, max, max+1} — six values that probe both edges.",
    whyItMatters: "Off-by-one errors (using < instead of <=, or vice versa) are one of the most common real-world bugs, and they only show up exactly at the boundary.",
    commonMistakes: "Testing only the exact min and max, or only testing values well inside the range and missing the edges entirely.",
  },
  {
    id: "bva-coupon-subtotal",
    mechanic: "bva",
    title: "Coupon Minimum Subtotal",
    technique: "Boundary Value Analysis",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "Brightbasket's SAVE20 coupon requires a subtotal between $100 and $500 (inclusive) to apply. List the boundary values you would test.",
    fieldLabel: "Subtotal ($)",
    min: 100,
    max: 500,
    hints: [
      "Same rule as always: probe both sides of each edge of the range.",
      "You need six values total, three around each edge.",
      "For 100–500: 99, 100, 101, 499, 500, 501.",
    ],
    explanation: "Even a business-rule threshold (not just a form field) deserves the same {min-1, min, min+1, max-1, max, max+1} treatment.",
    whyItMatters: "Pricing and eligibility thresholds directly affect revenue — an off-by-one here either blocks a valid discount or leaks one that shouldn't apply.",
    commonMistakes: "Forgetting that a business rule threshold is still a boundary worth testing, not just literal form-field limits.",
  },
  {
    id: "bva-review-length",
    mechanic: "bva",
    title: "Product Review Character Limit",
    technique: "Boundary Value Analysis",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt: "A product review field on Brightbasket must be between 10 and 500 characters. List the boundary values (as character counts) you would test.",
    fieldLabel: "Review length (characters)",
    min: 10,
    max: 500,
    hints: [
      "Think in terms of character counts, not the text itself.",
      "Still the same six-value pattern around each edge.",
      "For 10–500: 9, 10, 11, 499, 500, 501.",
    ],
    explanation: "Text-length constraints are boundaries too — count characters, not words, and test just under, at, and just over each limit.",
    whyItMatters: "Text fields often silently truncate or reject input at the wrong length due to counting bytes vs. characters, or off-by-one in the comparison.",
    commonMistakes: "Testing arbitrary short/long strings instead of the precise boundary lengths.",
  },

  // ─── Equivalence Partitioning ───────────────────────────────────────────
  {
    id: "ep-shipping-weight",
    mechanic: "equivalence-partitioning",
    title: "Shipping Weight Partitions",
    technique: "Equivalence Partitioning",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "Brightbasket accepts package weights from 1kg to 50kg for standard shipping. Classify each representative value as Valid or Invalid.",
    items: [
      { id: "1", label: "-5 kg", correctValid: false },
      { id: "2", label: "0 kg", correctValid: false },
      { id: "3", label: "1 kg", correctValid: true },
      { id: "4", label: "25 kg", correctValid: true },
      { id: "5", label: "50 kg", correctValid: true },
      { id: "6", label: "51 kg", correctValid: false },
      { id: "7", label: "1000 kg", correctValid: false },
    ],
    hints: [
      "Equivalence Partitioning groups inputs into classes that should behave the same way.",
      "There's one valid partition (1–50kg) and at least two invalid ones (below 1, above 50).",
      "Negative numbers and zero belong to the same 'too low' invalid partition as any number under 1.",
    ],
    explanation: "The valid partition is [1, 50]. Everything below 1 (including negative and zero) and everything above 50 are invalid partitions.",
    whyItMatters: "EP lets you test one representative value per partition instead of every possible number, dramatically cutting test volume without losing coverage.",
    commonMistakes: "Treating negative numbers as a 'different kind' of invalid from zero or from values just over the max — they're all just 'invalid', which is the point of partitioning.",
  },
  {
    id: "ep-cart-quantity",
    mechanic: "equivalence-partitioning",
    title: "Cart Quantity Partitions",
    technique: "Equivalence Partitioning",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "A Brightbasket product has 10 units in stock. Classify each candidate cart quantity as Valid or Invalid.",
    items: [
      { id: "1", label: "-1", correctValid: false },
      { id: "2", label: "0", correctValid: false },
      { id: "3", label: "1", correctValid: true },
      { id: "4", label: "5", correctValid: true },
      { id: "5", label: "10", correctValid: true },
      { id: "6", label: "11", correctValid: false },
      { id: "7", label: "999", correctValid: false },
    ],
    hints: [
      "Valid quantities are 1 through the available stock.",
      "A quantity of 0 isn't really 'in the cart' — it should be treated as invalid/remove.",
      "Anything above the stock level is invalid, no matter how large.",
    ],
    explanation: "Valid partition: [1, 10] (bounded by available stock). Invalid partitions: anything ≤ 0, and anything > 10.",
    whyItMatters: "Stock-dependent validity is a moving target — the same '11' could be valid for a different product with more stock, so tests must reason about partitions relative to the rule, not fixed numbers.",
    commonMistakes: "Assuming quantity validity is a fixed range instead of relative to current stock.",
  },
  {
    id: "ep-password-length",
    mechanic: "equivalence-partitioning",
    title: "Password Length Partitions",
    technique: "Equivalence Partitioning",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt: "Brightbasket registration requires passwords between 8 and 64 characters. Classify each candidate length as Valid or Invalid.",
    items: [
      { id: "1", label: "0 characters", correctValid: false },
      { id: "2", label: "3 characters", correctValid: false },
      { id: "3", label: "7 characters", correctValid: false },
      { id: "4", label: "8 characters", correctValid: true },
      { id: "5", label: "30 characters", correctValid: true },
      { id: "6", label: "64 characters", correctValid: true },
      { id: "7", label: "65 characters", correctValid: false },
    ],
    hints: [
      "There's exactly one valid partition here: [8, 64].",
      "Everything from 0 up to 7 characters falls in the same invalid 'too short' partition.",
      "Don't overthink it — 65+ characters is a single 'too long' partition regardless of how much too long.",
    ],
    explanation: "Valid: [8, 64]. Invalid partitions: [0, 7] (too short) and [65, ∞) (too long).",
    whyItMatters: "This is exactly the bug in Brightbasket's own registration form (BUG-002) when minimum-length enforcement is skipped — EP is how you'd have caught it systematically.",
    commonMistakes: "Picking multiple test values from within the same partition (e.g. both 1 and 3 characters) instead of one representative per partition plus the boundaries.",
  },

  // ─── Decision Table Testing ─────────────────────────────────────────────
  {
    id: "dt-coupon-eligibility",
    mechanic: "decision-table",
    title: "Coupon Discount Eligibility",
    technique: "Decision Table Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt:
      "Business rule: a discount applies only if the shopper has entered a coupon code AND the subtotal is over $50. Premium membership has no effect on this rule. For each rule row, choose the correct action.",
    conditionLabels: ["Premium Member?", "Has Coupon Code?", "Subtotal > $50?"],
    actionOptions: ["Apply discount", "No discount"],
    rules: [
      { id: "r1", conditions: { "Premium Member?": true, "Has Coupon Code?": true, "Subtotal > $50?": true }, action: "Apply discount" },
      { id: "r2", conditions: { "Premium Member?": true, "Has Coupon Code?": true, "Subtotal > $50?": false }, action: "No discount" },
      { id: "r3", conditions: { "Premium Member?": true, "Has Coupon Code?": false, "Subtotal > $50?": true }, action: "No discount" },
      { id: "r4", conditions: { "Premium Member?": false, "Has Coupon Code?": true, "Subtotal > $50?": true }, action: "Apply discount" },
      { id: "r5", conditions: { "Premium Member?": false, "Has Coupon Code?": false, "Subtotal > $50?": false }, action: "No discount" },
    ],
    hints: [
      "Read the business rule literally — it names exactly two required conditions.",
      "A condition not mentioned in the rule (Premium Member) shouldn't change the outcome at all.",
      "The discount only applies when BOTH 'Has Coupon Code' and 'Subtotal > $50' are true.",
    ],
    explanation: "The action depends only on (Has Coupon Code AND Subtotal > $50) — Premium Member status is a distractor condition that never changes the outcome.",
    whyItMatters: "Decision tables force you to enumerate every condition combination, which is exactly how BUG-017-style rules (thresholds calculated against the wrong basis) get caught before release.",
    commonMistakes: "Letting an irrelevant condition (like Premium Member here) influence your answer just because it's in the table.",
  },
  {
    id: "dt-shipping-fee",
    mechanic: "decision-table",
    title: "Shipping Fee Rules",
    technique: "Decision Table Testing",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt:
      "Business rules: Express shipping always incurs an express fee. Otherwise, shipping is free if the subtotal is $50 or more; below $50 a standard shipping fee applies. For each rule row, choose the correct action.",
    conditionLabels: ["Subtotal ≥ $50?", "Uses Express Shipping?"],
    actionOptions: ["Free Shipping", "Standard Shipping Fee", "Express Fee Applies"],
    rules: [
      { id: "r1", conditions: { "Subtotal ≥ $50?": true, "Uses Express Shipping?": true }, action: "Express Fee Applies" },
      { id: "r2", conditions: { "Subtotal ≥ $50?": true, "Uses Express Shipping?": false }, action: "Free Shipping" },
      { id: "r3", conditions: { "Subtotal ≥ $50?": false, "Uses Express Shipping?": true }, action: "Express Fee Applies" },
      { id: "r4", conditions: { "Subtotal ≥ $50?": false, "Uses Express Shipping?": false }, action: "Standard Shipping Fee" },
    ],
    hints: [
      "Express shipping is described as an override — check for it first.",
      "The free-shipping threshold only matters when Express isn't selected.",
      "There are exactly 4 rows for 2 boolean conditions (2×2) — make sure every combination is covered.",
    ],
    explanation: "Express Shipping always wins (rows 1 and 3 both result in the express fee), regardless of subtotal. Only when Express is false does the $50 threshold decide Free vs. Standard.",
    whyItMatters: "Overlapping/overriding rules like this are exactly where hand-written if/else logic tends to get the precedence wrong.",
    commonMistakes: "Applying the free-shipping threshold even when Express Shipping is selected, ignoring that Express overrides it.",
  },

  // ─── State Transition Testing ───────────────────────────────────────────
  {
    id: "st-login-lockout",
    mechanic: "state-transition",
    title: "Login Attempt Lockout",
    technique: "State Transition Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt:
      "Brightbasket locks an account after 2 consecutive failed login attempts. A successful login from Active resets nothing (it's already fine); from a Failed state it returns to Active. Mark each candidate transition as Valid or Invalid.",
    states: ["Active", "Failed(1)", "Failed(2)/Locked"],
    diagramDescription:
      "Active --(wrong password)--> Failed(1) --(wrong password)--> Locked. Failed(1) --(correct password)--> Active. Locked cannot be exited by logging in again.",
    transitions: [
      { id: "t1", from: "Active", to: "Failed(1)", expectedValid: true },
      { id: "t2", from: "Failed(1)", to: "Failed(2)/Locked", expectedValid: true },
      { id: "t3", from: "Failed(1)", to: "Active", expectedValid: true },
      { id: "t4", from: "Failed(2)/Locked", to: "Active", expectedValid: false },
      { id: "t5", from: "Active", to: "Failed(2)/Locked", expectedValid: false },
    ],
    hints: [
      "Only one failed attempt moves you one step at a time — you can't skip a state.",
      "A correct password from a Failed state should recover to Active.",
      "Once Locked, logging in again (even correctly) shouldn't be a way out — that would defeat the lockout.",
    ],
    explanation: "Valid transitions are Active→Failed(1), Failed(1)→Failed(2)/Locked, and Failed(1)→Active (on a correct password). Locked→Active and Active→Locked (skipping a step) are invalid.",
    whyItMatters: "Auth state machines are a common source of real security bugs — an invalid transition here could mean lockouts don't actually protect the account.",
    commonMistakes: "Assuming a correct password always resets you to Active, even from a Locked state — that would make the lockout meaningless.",
  },
  {
    id: "st-order-lifecycle",
    mechanic: "state-transition",
    title: "Order Status Lifecycle",
    technique: "State Transition Testing",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt:
      "Brightbasket orders move Placed → Shipped → Delivered. An order can be Cancelled only while still Placed. A Delivered order can be Returned, but a Shipped (not yet Delivered) order cannot be Returned directly. Mark each candidate transition as Valid or Invalid.",
    states: ["Placed", "Shipped", "Delivered", "Cancelled", "Returned"],
    diagramDescription:
      "Placed --> Shipped --> Delivered --> Returned. Placed --> Cancelled. No other transitions exist.",
    transitions: [
      { id: "t1", from: "Placed", to: "Shipped", expectedValid: true },
      { id: "t2", from: "Placed", to: "Cancelled", expectedValid: true },
      { id: "t3", from: "Shipped", to: "Delivered", expectedValid: true },
      { id: "t4", from: "Delivered", to: "Returned", expectedValid: true },
      { id: "t5", from: "Shipped", to: "Returned", expectedValid: false },
      { id: "t6", from: "Delivered", to: "Cancelled", expectedValid: false },
    ],
    hints: [
      "Cancellation is only described as available from one specific state.",
      "Returns require the order to have actually arrived first.",
      "An order that's already Delivered has passed the point where 'cancel' makes sense.",
    ],
    explanation: "Cancelled is only reachable from Placed. Returned is only reachable from Delivered — Shipped→Returned skips a required state.",
    whyItMatters: "Letting a 'Cancel' button remain active on a Delivered order (or a 'Return' button on a merely Shipped one) is a realistic UI/state bug that confuses customers and support teams alike.",
    commonMistakes: "Assuming any 'earlier' state can transition to any 'later' one, without checking whether the specific path is actually defined.",
  },

  // ─── Error Guessing ─────────────────────────────────────────────────────
  {
    id: "eg-coupons",
    mechanic: "error-guessing",
    title: "Error Guessing: Coupon Codes",
    technique: "Error Guessing",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt: "Use error guessing — drawing on experience rather than formal test design — to predict likely defects before you even start testing.",
    context: "Based on experience, list the kinds of problems you'd guess could exist in Brightbasket's coupon code feature — before even testing it.",
    keywordGroups: [
      ["expired coupon still works", "expiry not checked"],
      ["case sensitivity", "lowercase vs uppercase code"],
      ["leading or trailing whitespace", "extra spaces in code"],
      ["applying the same coupon twice", "discount stacking"],
      ["minimum subtotal not enforced", "threshold ignored"],
    ],
    hints: [
      "Think about what a lazy or rushed implementation might forget to check.",
      "Text input fields (like a coupon code) commonly have formatting-related bugs.",
      "Anything involving 'applying twice' or 'clicking twice' is a classic idempotency guess.",
    ],
    explanation: "Experienced testers guess at common failure patterns — expiry checks being skipped, case/whitespace handling, double-application, and threshold logic — before writing a single formal test case.",
    whyItMatters: "Several of these guesses are exactly the real bugs seeded in Brightbasket (expired coupons, stacked discounts) — error guessing built on experience finds real issues fast.",
    commonMistakes: "Guessing only UI-level issues (button color, spacing) instead of logic/business-rule failures, which are usually higher-impact.",
  },
  {
    id: "eg-checkout-payment",
    mechanic: "error-guessing",
    title: "Error Guessing: Checkout & Payment",
    technique: "Error Guessing",
    difficulty: "Expert",
    xp: XP.Expert,
    prompt: "Use error guessing — drawing on experience rather than formal test design — to predict likely defects before you even start testing.",
    context: "Based on experience, list the kinds of problems you'd guess could exist in Brightbasket's checkout and payment flow.",
    keywordGroups: [
      ["duplicate order on double click", "double submit creates two orders"],
      ["empty or incomplete address accepted", "missing required address fields"],
      ["invalid card number format accepted", "no card validation"],
      ["price mismatch between cart and checkout", "stale price used"],
      ["race condition on stock", "concurrent orders oversell stock"],
    ],
    hints: [
      "Checkout is a multi-step form — think about what happens if a step is skipped or repeated.",
      "Anything involving money or payment fields is worth guessing hard about input validation.",
      "Consider what happens with fast, repeated, or concurrent actions, not just single careful ones.",
    ],
    explanation: "High-value flows like checkout attract error guesses around duplication (double-clicks), incomplete data slipping through, and consistency between what's displayed and what's charged.",
    whyItMatters: "This is exactly the profile of bugs seeded in Brightbasket's checkout (duplicate orders, empty addresses, price mismatches) — the kind of thing a rushed release is most likely to ship.",
    commonMistakes: "Only imagining the 'happy path done twice' instead of also considering data validation and cross-module consistency (e.g. price shown vs. price charged).",
  },

  // ─── Generic Scenario Challenges (remaining technique types) ───────────
  {
    id: "sc-functional-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Functional Testing: Add to Cart",
    technique: "Functional Testing",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "You're functionally testing the 'Add to Cart' button on Brightbasket. Select the actions that are FUNCTIONAL test checks.",
    options: [
      { id: "1", label: "Click Add to Cart on an in-stock product and verify it appears in the cart", correct: true },
      { id: "2", label: "Click Add to Cart twice and verify the quantity increments correctly", correct: true },
      { id: "3", label: "Resize the browser window to check the button doesn't overlap other elements", correct: false },
      { id: "4", label: "Verify the cart icon's item count updates after adding", correct: true },
      { id: "5", label: "Measure how many milliseconds the click takes to respond", correct: false },
      { id: "6", label: "Add an out-of-stock product and verify it's rejected", correct: true },
    ],
    hints: [
      "Functional testing verifies that a feature does what it's supposed to do, based on inputs and outputs.",
      "Layout and timing checks belong to other testing types (UI, Performance), not Functional.",
      "Anything about correct behavior — what happens after an action — is functional.",
    ],
    explanation: "Functional checks verify behavior and outcomes (cart contents, quantities, stock rules) — not layout (UI testing) or speed (performance testing).",
    whyItMatters: "Mixing testing types under one label makes it harder to know what's actually been verified — a feature can be 'functionally correct' yet still look broken or be slow.",
    commonMistakes: "Lumping every kind of check together as 'testing the feature' instead of being precise about which quality attribute is being verified.",
  },
  {
    id: "sc-functional-2",
    mechanic: "scenario",
    mode: "short-answer",
    title: "Functional Testing: Coupon Application",
    technique: "Functional Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "Describe what you would functionally verify when a shopper applies a valid coupon code at checkout.",
    keywordGroups: [
      ["discount amount is correct", "percentage applied correctly"],
      ["total is recalculated", "updated total shown"],
      ["coupon code is stored with the order", "order record reflects coupon used"],
    ],
    hints: [
      "Think about the full chain of effects a valid coupon should trigger.",
      "Consider both what's displayed and what's actually persisted.",
      "The discount, the total, and the saved order record are three separate things to check.",
    ],
    explanation: "A complete functional check confirms the discount math, the recalculated total shown to the user, and that the applied coupon is correctly recorded on the resulting order.",
    whyItMatters: "It's easy to verify the on-screen total looks right while missing that the coupon was never actually saved with the order — a gap that surfaces later in reporting or support.",
    commonMistakes: "Stopping at 'the total looks right' without checking that the underlying order record is consistent.",
  },
  {
    id: "sc-smoke-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Smoke Testing a New Build",
    technique: "Smoke Testing",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "A new Brightbasket build just deployed. Select the checks that belong in a SMOKE test (not full regression).",
    options: [
      { id: "1", label: "Login works", correct: true },
      { id: "2", label: "The product catalog loads", correct: true },
      { id: "3", label: "Add to cart works for at least one product", correct: true },
      { id: "4", label: "Every single product's rating rounds correctly", correct: false },
      { id: "5", label: "A basic checkout completes end-to-end", correct: true },
      { id: "6", label: "Every coupon code in the system is individually verified", correct: false },
    ],
    hints: [
      "Smoke testing asks 'is the build stable enough to test further?' — not 'is everything correct?'",
      "Keep it to the most critical, high-level flows.",
      "Exhaustive, detail-level checks belong to later regression testing, not smoke.",
    ],
    explanation: "Smoke tests are a small, fast set of critical-path checks (login, browse, cart, checkout) meant to catch a broken build early — not exhaustive coverage.",
    whyItMatters: "Running full regression on a fundamentally broken build wastes hours; a 5-minute smoke test catches catastrophic failures immediately.",
    commonMistakes: "Turning the smoke test into a mini regression suite, which defeats its purpose of being fast.",
  },
  {
    id: "sc-smoke-2",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Smoke Testing After a Hotfix",
    technique: "Smoke Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "A hotfix was just deployed to the Checkout module only. Select the appropriate smoke test scope.",
    options: [
      { id: "1", label: "Verify checkout completes successfully for a basic order", correct: true },
      { id: "2", label: "Verify login and catalog browsing still work (nothing else broke)", correct: true },
      { id: "3", label: "Re-test every Manual Testing Playground challenge", correct: false },
      { id: "4", label: "Verify the specific area the hotfix touched behaves correctly", correct: true },
      { id: "5", label: "Audit every product's description text for typos", correct: false },
    ],
    hints: [
      "Smoke testing after a targeted fix still checks the overall app is stable, not just the fixed area.",
      "Unrelated, low-priority content checks don't belong in a smoke test.",
      "The fixed area itself should always be included.",
    ],
    explanation: "A good smoke test after a hotfix confirms both that critical unrelated flows are unaffected and that the fixed area now works.",
    whyItMatters: "A hotfix can have unintended side effects elsewhere — smoke testing catches that quickly before deeper regression testing begins.",
    commonMistakes: "Only checking the specific fix and assuming nothing else could have been affected.",
  },
  {
    id: "sc-sanity-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Sanity Check After a Bug Fix",
    technique: "Sanity Testing",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "The dev team just fixed BUG-015 (expired coupons being accepted). Select the right SANITY checks before continuing full testing.",
    options: [
      { id: "1", label: "Re-apply the expired EXPIRED5 coupon and confirm it's now rejected", correct: true },
      { id: "2", label: "Re-run the entire regression suite", correct: false },
      { id: "3", label: "Verify checkout still completes with a valid, unexpired coupon", correct: true },
      { id: "4", label: "Check the visual color of the coupon input box", correct: false },
      { id: "5", label: "Confirm the fix didn't break the still-valid WELCOME10 coupon", correct: true },
    ],
    hints: [
      "Sanity testing is a narrow, focused check on the specific fix and its immediate neighbors.",
      "Running the full suite is regression testing, not sanity — sanity is meant to be quick.",
      "Unrelated visual details aren't part of a sanity check for a logic bug.",
    ],
    explanation: "Sanity testing narrowly confirms the specific fix works and its close neighbors weren't broken — not a full suite re-run.",
    whyItMatters: "Sanity checks let you quickly decide 'is this fix good enough to move on' without the time cost of full regression on every single change.",
    commonMistakes: "Confusing sanity testing with regression testing and re-running everything for a small, targeted fix.",
  },
  {
    id: "sc-sanity-2",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Sanity Check on a Config Change",
    technique: "Sanity Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "The free-shipping threshold was just changed from $50 to $75. Select the right sanity checks.",
    options: [
      { id: "1", label: "Verify an order just under $75 now gets a shipping fee", correct: true },
      { id: "2", label: "Verify an order at or above $75 still gets free shipping", correct: true },
      { id: "3", label: "Re-test every coupon code in the system", correct: false },
      { id: "4", label: "Verify the old $50 threshold no longer grants free shipping on its own", correct: true },
    ],
    hints: [
      "Focus only on behavior tied to the changed threshold.",
      "Unrelated features (coupons) aren't part of this sanity check.",
      "Check both sides of the new threshold, and that the old one no longer applies.",
    ],
    explanation: "A sanity check for a threshold change verifies the new value behaves correctly on both sides, and that the old value's behavior no longer lingers.",
    whyItMatters: "Configuration changes are easy to get 'half applied' (e.g. UI text updated but logic still using the old value) — a quick sanity check catches that immediately.",
    commonMistakes: "Assuming a config change is purely cosmetic and skipping behavioral verification.",
  },
  {
    id: "sc-regression-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Regression Scope After a Cart Fix",
    technique: "Regression Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "BUG-011 (quantity 0 leaving a $0 cart item) was just fixed. Select the areas worth regression testing.",
    options: [
      { id: "1", label: "Cart quantity stepper behavior", correct: true },
      { id: "2", label: "Cart subtotal calculation", correct: true },
      { id: "3", label: "Checkout total calculation", correct: true },
      { id: "4", label: "Product search relevance ranking", correct: false },
      { id: "5", label: "Order history item count after placing an order affected by this case", correct: true },
    ],
    hints: [
      "Trace forward from the cart through every screen that depends on cart data.",
      "Unrelated modules (like search) don't need regression testing for this fix.",
      "Anything that reads cart totals downstream is in scope.",
    ],
    explanation: "Regression scope follows the data: cart quantity affects cart totals, which affects checkout totals, which affects the resulting order record.",
    whyItMatters: "A narrow view of 'just re-test the button I fixed' misses the downstream effects where the real damage from a pricing bug often shows up.",
    commonMistakes: "Regression testing only the exact screen that was fixed, ignoring everything downstream that consumes the same data.",
  },
  {
    id: "sc-regression-2",
    mechanic: "scenario",
    mode: "short-answer",
    title: "Why Regress Checkout After a Pricing Change",
    technique: "Regression Testing",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt: "Explain why you'd regression test the Checkout flow after a change to pricing logic, even if the change was only in the Coupons module.",
    keywordGroups: [
      ["checkout depends on pricing", "shared pricing calculation logic"],
      ["side effects in unrelated areas", "totals could be affected elsewhere"],
      ["automated regression suite", "re-run existing tests to confirm nothing broke"],
    ],
    hints: [
      "Think about shared code — does Coupons calculate its own totals, or feed into a shared pricing function?",
      "Regression testing exists specifically to catch effects the developer didn't anticipate.",
      "Mention how automation makes this practical to do on every change.",
    ],
    explanation: "Checkout consumes the same shared pricing calculation that Coupons feeds into, so a change there can silently affect totals shown and charged at checkout — exactly what regression testing exists to catch.",
    whyItMatters: "Modules that look separate in the UI often share logic underneath; skipping regression on 'unrelated' areas is how side effects slip into production.",
    commonMistakes: "Assuming a change is isolated just because it was made in a different module's code.",
  },
  {
    id: "sc-retesting-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Retesting BUG-018 After a Fix",
    technique: "Retesting",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "BUG-018 (empty address allowed at checkout) has supposedly been fixed. Select what retesting should include.",
    options: [
      { id: "1", label: "Repeat the exact original steps that found the bug", correct: true },
      { id: "2", label: "Confirm a completely empty address is now rejected", correct: true },
      { id: "3", label: "Test an unrelated feature like the Wishlist", correct: false },
      { id: "4", label: "Try partial-empty combinations too (only city empty, only postal code empty)", correct: true },
      { id: "5", label: "Assume it's fixed because the developer said so, without checking", correct: false },
    ],
    hints: [
      "Retesting always starts by reproducing the exact original failing steps.",
      "It's worth going slightly beyond the exact original steps to check nearby variations.",
      "Retesting is about THIS bug specifically, not unrelated features.",
    ],
    explanation: "Retesting means re-running the original failing scenario, confirming it now passes, and probing closely related variations — not testing unrelated areas or trusting a claim without verification.",
    whyItMatters: "Bugs are sometimes 'fixed' for the exact reported steps but still broken for a slightly different path (e.g. only one field left empty) — retesting only the literal original steps can miss that.",
    commonMistakes: "Treating retesting as identical to regression testing, or skipping verification entirely based on developer assurance.",
  },
  {
    id: "sc-exploratory-1",
    mechanic: "scenario",
    mode: "short-answer",
    title: "Exploring the Wishlist Feature",
    technique: "Exploratory Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "You have 15 minutes to explore Brightbasket's Wishlist feature with no test cases. What would you focus on?",
    keywordGroups: [
      ["adding and removing items repeatedly", "toggle add/remove"],
      ["duplicate entries", "adding the same item twice"],
      ["moving an item from wishlist to cart", "wishlist to cart flow"],
      ["empty wishlist state", "no items message"],
    ],
    hints: [
      "Think about repeated/rapid actions, not just a single clean pass.",
      "Consider the feature's edge states (empty, full, duplicated).",
      "Consider how this feature connects to another (Cart).",
    ],
    explanation: "Good exploratory sessions probe repeated actions, edge states (empty/duplicated), and integration points with other features — following curiosity rather than a script.",
    whyItMatters: "Exploratory testing is exactly how BUG-013 (duplicate wishlist entries) and BUG-014 (undo not working) would realistically be found — no formal test case predicted them.",
    commonMistakes: "Only clicking through the feature once in the 'intended' way instead of trying repeated, unusual, or edge-case interactions.",
  },
  {
    id: "sc-exploratory-2",
    mechanic: "scenario",
    mode: "short-answer",
    title: "Investigating a Checkout Flicker",
    technique: "Exploratory Testing",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt: "While exploring Checkout, you notice the total briefly flickers when applying a coupon. What follow-up investigation would you do?",
    keywordGroups: [
      ["reproduce consistently", "does it happen every time"],
      ["check console or network tab", "inspect for errors"],
      ["try different coupons or amounts", "test with various discount values"],
      ["log it with clear repro steps", "document as a bug"],
    ],
    hints: [
      "First establish whether it's reliably reproducible or intermittent.",
      "Browser dev tools (console, network) are a tester's best friend for investigating odd UI behavior.",
      "Vary the inputs (different coupons, amounts) to see if the flicker is data-dependent.",
    ],
    explanation: "A good exploratory follow-up establishes reproducibility, inspects dev tools for clues, varies the inputs to isolate the trigger, and documents findings clearly.",
    whyItMatters: "A 'flicker' can be a symptom of a real double-calculation bug (like BUG-016's coupon stacking) rather than just a cosmetic glitch — it deserves real investigation before being dismissed.",
    commonMistakes: "Dismissing a visual glitch as 'just a rendering thing' without checking whether it reflects an actual double-calculation happening underneath.",
  },
  {
    id: "sc-adhoc-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Recognizing Ad-hoc Testing",
    technique: "Ad-hoc Testing",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "Select the activities that best describe AD-HOC testing being performed on Brightbasket.",
    options: [
      { id: "1", label: "Randomly clicking through checkout with no plan, just to see what breaks", correct: true },
      { id: "2", label: "Following a documented test case step by step", correct: false },
      { id: "3", label: "Trying unusual input combinations on a whim", correct: true },
      { id: "4", label: "Testing based on intuition and experience, with no formal documentation", correct: true },
      { id: "5", label: "Executing the automated regression suite", correct: false },
    ],
    hints: [
      "Ad-hoc testing has no plan, script, or documentation at all — it's the least structured technique.",
      "Anything involving following a pre-written test case is NOT ad-hoc.",
      "Whim and intuition are the defining traits here.",
    ],
    explanation: "Ad-hoc testing is entirely unstructured and undocumented — driven by intuition, unlike exploratory testing which is unscripted but still purposeful and time-boxed.",
    whyItMatters: "Recognizing the difference between ad-hoc and exploratory testing helps a team decide when each is appropriate — ad-hoc is quick and informal, exploratory is more disciplined.",
    commonMistakes: "Confusing ad-hoc testing with exploratory testing — exploratory testing usually has a mission/charter even without formal test cases.",
  },
  {
    id: "sc-acceptance-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "User Acceptance Testing for Checkout",
    technique: "Acceptance Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "Select the activities that represent User Acceptance Testing (UAT) for the Checkout feature.",
    options: [
      { id: "1", label: "Business stakeholders verify checkout matches the agreed acceptance criteria", correct: true },
      { id: "2", label: "Developers unit test the pricing calculation function", correct: false },
      { id: "3", label: "End users try placing a real order in a staging environment", correct: true },
      { id: "4", label: "Automated tests validate the checkout API's response schema", correct: false },
      { id: "5", label: "Confirming the feature meets business requirements before sign-off", correct: true },
    ],
    hints: [
      "UAT is performed by (or on behalf of) the business/end users, not developers.",
      "Unit tests and API schema checks are technical, developer-facing checks — not UAT.",
      "UAT's purpose is a go/no-go sign-off against business requirements.",
    ],
    explanation: "UAT is about business stakeholders or real users confirming the feature meets requirements well enough to accept/sign off — not technical, code-level verification.",
    whyItMatters: "A feature can pass every technical test yet still fail UAT if it doesn't actually solve the business problem the way stakeholders expected.",
    commonMistakes: "Treating any late-stage testing as 'UAT' regardless of who's performing it or what they're checking against.",
  },
  {
    id: "sc-acceptance-2",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Acceptance Criteria for Password Reset",
    technique: "Acceptance Testing",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt: "Select the checks that belong in ACCEPTANCE testing sign-off for the password reset feature.",
    options: [
      { id: "1", label: "A registered user can successfully reset their password end-to-end", correct: true },
      { id: "2", label: "The reset email is sent within an acceptable time and looks correct", correct: true },
      { id: "3", label: "The internal token-generation function has 100% code coverage", correct: false },
      { id: "4", label: "Stakeholders confirm the flow matches the originally agreed user story", correct: true },
    ],
    hints: [
      "Code coverage is a developer/unit-testing concern, not an acceptance criterion.",
      "Focus on outcomes a business stakeholder or end user would actually check.",
      "The email itself (content, timing) is part of the user-facing experience being accepted.",
    ],
    explanation: "Acceptance testing checks end-to-end, business-visible outcomes against the agreed user story — not internal code metrics like coverage.",
    whyItMatters: "Sign-off should be based on what the business actually asked for, not on technical implementation details that don't affect the user experience.",
    commonMistakes: "Including internal/technical metrics (like code coverage) as if they were acceptance criteria.",
  },
  {
    id: "sc-system-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "System Testing the Full Flow",
    technique: "System Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "Select the check that qualifies as SYSTEM testing (the complete, integrated application).",
    options: [
      { id: "1", label: "A user can search, add to cart, apply a coupon, and complete checkout in one flow", correct: true },
      { id: "2", label: "The formatRating function is unit tested in isolation", correct: false },
      { id: "3", label: "The whole app works correctly together with its database and all modules", correct: true },
      { id: "4", label: "A single UI button component is tested in isolation (e.g. in Storybook)", correct: false },
    ],
    hints: [
      "System testing exercises the whole, integrated product — not a single function or component.",
      "If it involves 'the entire app working together', it's system-level.",
      "Isolated unit or component tests are a different (lower) level of testing.",
    ],
    explanation: "System testing verifies the complete, integrated application behaves correctly as a whole — the opposite of testing an isolated function or component.",
    whyItMatters: "A system can pass every unit test yet fail at the system level if the pieces don't integrate correctly — system testing is what catches that gap.",
    commonMistakes: "Confusing 'testing a big feature' with system testing when it's still really just testing one component or function in isolation.",
  },
  {
    id: "sc-integration-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Integration Between Cart and Coupons",
    technique: "Integration Testing",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt: "Select the checks that test the INTEGRATION between the Cart and Coupons modules specifically.",
    options: [
      { id: "1", label: "The discount calculated by Coupons correctly reduces the Cart's displayed total", correct: true },
      { id: "2", label: "The coupon input field accepts typed text", correct: false },
      { id: "3", label: "When cart items change, the applied coupon's discount recalculates correctly", correct: true },
      { id: "4", label: "The wishlist heart icon renders correctly", correct: false },
    ],
    hints: [
      "Integration testing is about the handoff/interaction between two modules, not either module alone.",
      "A field simply accepting text is a unit/UI-level check, not integration.",
      "Look for checks where a change in one module should visibly affect the other.",
    ],
    explanation: "Integration testing here focuses on the interface between Cart and Coupons — does a discount from one correctly propagate into the other's totals, including when the cart changes.",
    whyItMatters: "Modules that work perfectly alone can still fail when combined — integration testing is where those seams are verified.",
    commonMistakes: "Testing each module's own basic functionality and calling it 'integration testing' without actually exercising the connection between them.",
  },
  {
    id: "sc-e2e-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "A True End-to-End Test",
    technique: "End-to-End Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "Select the scenario that qualifies as a true END-TO-END (E2E) test of Brightbasket.",
    options: [
      { id: "1", label: "Register a new account, search for a product, add it to cart, apply a coupon, complete checkout, and view it in order history", correct: true },
      { id: "2", label: "Test only the Add to Cart button in isolation", correct: false },
      { id: "3", label: "Verify the database schema for the orders table", correct: false },
      { id: "4", label: "Log in and immediately stop without doing anything else", correct: false },
    ],
    hints: [
      "E2E means following a complete, realistic user journey from start to finish.",
      "A single isolated action is not end-to-end, no matter how important that action is.",
      "The journey should end at a meaningful outcome (e.g. an order appearing in history), not stop partway.",
    ],
    explanation: "E2E testing follows a full realistic user journey across multiple features to a meaningful conclusion — not an isolated action or a partial flow.",
    whyItMatters: "Bugs often hide in the handoffs between steps of a journey (e.g. a coupon applied in one step not surviving to the final order) — only a true E2E test catches those.",
    commonMistakes: "Calling any multi-step test 'E2E' even when it doesn't represent a complete, realistic user journey.",
  },
  {
    id: "sc-compatibility-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Compatibility Testing Concerns",
    technique: "Compatibility Testing",
    difficulty: "Advanced",
    xp: XP.Advanced,
    prompt: "Select the checks that are COMPATIBILITY testing concerns for Brightbasket.",
    options: [
      { id: "1", label: "Checkout works correctly in both Chrome and Firefox", correct: true },
      { id: "2", label: "The layout renders correctly on a 375px-wide mobile screen", correct: true },
      { id: "3", label: "The coupon discount math is correct", correct: false },
      { id: "4", label: "The app works on both Windows and macOS", correct: true },
      { id: "5", label: "Bug severity levels are labeled consistently", correct: false },
    ],
    hints: [
      "Compatibility testing is about consistent behavior across different environments (browsers, devices, OSes).",
      "Business logic correctness (like discount math) isn't a compatibility concern.",
      "Screen size and OS/browser combinations are the classic compatibility axes.",
    ],
    explanation: "Compatibility testing verifies consistent behavior across browsers, devices, screen sizes, and operating systems — not the correctness of business logic itself.",
    whyItMatters: "A feature can be functionally perfect in Chrome yet break entirely in Firefox or on a small screen — compatibility testing is the only technique that catches that.",
    commonMistakes: "Treating a single-browser desktop pass as 'fully tested' without checking other browsers, devices, or screen sizes.",
  },
  {
    id: "sc-compatibility-2",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Compatibility Testing a Layout Bug",
    technique: "Compatibility Testing",
    difficulty: "Expert",
    xp: XP.Expert,
    prompt: "The product grid overflows on narrow screens (BUG-024). Select the right compatibility test approach to confirm the scope of the problem.",
    options: [
      { id: "1", label: "Test at several viewport widths (e.g. 320px, 375px, 768px, 1024px)", correct: true },
      { id: "2", label: "Test only in one desktop browser at full width", correct: false },
      { id: "3", label: "Check whether the issue also appears in both portrait and landscape orientation", correct: true },
      { id: "4", label: "Verify the discount percentage math is still correct on mobile", correct: false },
    ],
    hints: [
      "A responsive layout bug needs to be checked across a *range* of widths, not just one.",
      "Orientation (portrait/landscape) is a real compatibility axis for mobile layouts.",
      "Stick to layout/rendering checks — don't drift into unrelated business logic.",
    ],
    explanation: "Confirming the scope of a responsive layout bug means testing a spread of realistic viewport widths and both orientations — not just one arbitrary size.",
    whyItMatters: "A fix verified at only one screen width might still be broken at other common breakpoints — thorough compatibility testing avoids re-opening the same bug class.",
    commonMistakes: "Confirming a responsive fix at only the exact width that was originally reported broken, missing nearby widths that behave differently.",
  },
  {
    id: "sc-usability-1",
    mechanic: "scenario",
    mode: "short-answer",
    title: "Usability Issues on Checkout",
    technique: "Usability Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "What usability issues would you look for on the Brightbasket checkout page?",
    keywordGroups: [
      ["clear error messages", "understandable validation feedback"],
      ["logical field order", "intuitive form flow"],
      ["required fields clearly marked", "visible indication of required fields"],
      ["easy to correct mistakes", "can edit before final submission"],
    ],
    hints: [
      "Usability is about how easy and pleasant the flow is to use, not whether it's technically correct.",
      "Think about a first-time user who's never seen this form before.",
      "Error handling and recoverability are core usability concerns.",
    ],
    explanation: "Good usability review looks at clarity of errors, logical flow, visible requirements, and how easily a user can fix mistakes before submitting.",
    whyItMatters: "A checkout that's functionally perfect but confusing to use still costs a business real sales through cart abandonment.",
    commonMistakes: "Focusing only on whether the form works correctly, without considering whether a real user would find it clear and easy.",
  },
  {
    id: "sc-ui-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "UI Testing vs. Functional Testing",
    technique: "UI Testing",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "Select the checks that are UI testing concerns (visual/presentation), not functional correctness.",
    options: [
      { id: "1", label: "Buttons are aligned and text is readable", correct: true },
      { id: "2", label: "The discount amount is calculated correctly", correct: false },
      { id: "3", label: "Text doesn't overflow its container", correct: true },
      { id: "4", label: "Colors have sufficient contrast for readability", correct: true },
      { id: "5", label: "The coupon code check is case-insensitive", correct: false },
    ],
    hints: [
      "UI testing is about how things look and are laid out, not what they compute.",
      "Anything about correctness of a calculation is functional, not UI.",
      "Contrast, alignment, and overflow are classic UI checks.",
    ],
    explanation: "UI testing covers visual presentation — alignment, readability, overflow, contrast — while correctness of calculations and business rules is functional testing.",
    whyItMatters: "A screen can look perfect and be functionally wrong, or compute correctly and look broken — the two need to be tested separately to know which is which.",
    commonMistakes: "Treating a visually clean screen as proof the underlying logic is also correct.",
  },
  {
    id: "sc-negative-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Negative Test Cases for Registration",
    technique: "Negative Testing",
    difficulty: "Intermediate",
    xp: XP.Intermediate,
    prompt: "Select the NEGATIVE test cases for the Brightbasket registration form.",
    options: [
      { id: "1", label: "Submit with a valid email and a strong password", correct: false },
      { id: "2", label: "Submit with an email that's already registered", correct: true },
      { id: "3", label: "Submit with an empty password field", correct: true },
      { id: "4", label: "Submit with a password of only 1 character", correct: true },
      { id: "5", label: "Submit with every field filled out correctly", correct: false },
    ],
    hints: [
      "Negative tests deliberately use invalid, unexpected, or forbidden input.",
      "Anything that should succeed if the system works correctly is a positive test, not negative.",
      "Duplicate emails and under-length passwords are classic negative cases.",
    ],
    explanation: "Negative tests intentionally violate expected input rules (duplicate email, empty/short password) to confirm the system correctly rejects them.",
    whyItMatters: "Systems are usually well-tested for the happy path already — negative testing is what actually finds validation gaps like BUG-002 (weak passwords accepted).",
    commonMistakes: "Writing only 'slightly wrong' negative cases and missing extreme ones like a completely empty required field.",
  },
  {
    id: "sc-positive-1",
    mechanic: "scenario",
    mode: "multi-select",
    title: "Positive Test Cases for Login",
    technique: "Positive Testing",
    difficulty: "Beginner",
    xp: XP.Beginner,
    prompt: "Select the POSITIVE test cases for the Brightbasket login form.",
    options: [
      { id: "1", label: "Log in with a registered email and the correct password", correct: true },
      { id: "2", label: "Log in with an unregistered email", correct: false },
      { id: "3", label: "Log in with correct credentials and verify redirect to the shop home page", correct: true },
      { id: "4", label: "Log in with an empty password field", correct: false },
    ],
    hints: [
      "Positive tests use valid, expected input and confirm the system behaves correctly.",
      "Anything using wrong or missing credentials is a negative test, not positive.",
      "Checking the resulting redirect/outcome is part of confirming the happy path works.",
    ],
    explanation: "Positive tests use correct, expected input (valid email + correct password) and verify the expected successful outcome, like a redirect after login.",
    whyItMatters: "Positive testing confirms the core feature actually works for legitimate users — the baseline every other test type builds on.",
    commonMistakes: "Verifying only that no error appeared, without confirming the actually expected successful outcome (like a redirect) occurred.",
  },
];

export function getChallengeById(id: string): Challenge | undefined {
  return CHALLENGES.find((c) => c.id === id);
}

export const TECHNIQUES = Array.from(new Set(CHALLENGES.map((c) => c.technique)));
