import type { Article, Quiz, FlashcardSet } from "../types";

export const MANUAL_TESTING_ARTICLES: Article[] = [
  {
    id: "mt-introduction",
    moduleId: "manual-testing",
    slug: "introduction-to-software-testing",
    title: "Introduction to Software Testing",
    summary: "What testing is, why it exists, and how it fits into building reliable software.",
    readingTimeMin: 6,
    definition:
      "Software testing is the process of evaluating a system or its components to find whether it satisfies specified requirements, and to identify defects before the software reaches its users.",
    explanation: [
      "Testing is not just 'trying to break the app' — it's a disciplined investigation. A tester builds a model of how the system should behave, then designs experiments (test cases) that compare actual behavior against that model.",
      "No amount of testing can prove software is 100% defect-free — testing can only show the presence of defects, not their absence (Dijkstra's principle). The goal is to reduce risk to an acceptable level, not to reach zero risk.",
      "Testing spans the entire software lifecycle, not just a phase after coding. Reviewing a requirements document for ambiguity is testing. Reviewing a design for a missing edge case is testing. The earlier a defect is found, the cheaper it is to fix.",
    ],
    examples: [
      { language: "text", caption: "Cost of finding a defect at different stages (illustrative)", code: "Requirements:  1x\nDesign:        3-6x\nCoding:        10x\nTesting:       15-40x\nProduction:    30-100x" },
    ],
    advantages: [
      "Catches defects before customers do, protecting revenue and reputation.",
      "Gives objective evidence of quality (or its absence) to support release decisions.",
      "Reduces the cost of fixing defects by finding them earlier in the lifecycle.",
    ],
    disadvantages: [
      "Cannot guarantee a defect-free product — exhaustive testing is practically impossible for any non-trivial system.",
      "Adds time and cost to a project, which is sometimes seen (wrongly) as pure overhead rather than risk reduction.",
    ],
    diagrams: [
      {
        title: "Where testing fits in delivering software",
        code: "flowchart LR\n  A[Requirements] --> B[Design]\n  B --> C[Development]\n  C --> D[Testing]\n  D --> E[Release]\n  D -. defects found .-> C\n  A -. reviewed for testability .-> D",
      },
    ],
    commonMistakes: [
      "Treating testing as a phase that only starts after coding is 'done'.",
      "Equating 'no bugs found' with 'no bugs exist'.",
      "Testing only the happy path and skipping negative/edge cases.",
    ],
    bestPractices: [
      "Get testers involved during requirements and design, not just after a build is ready.",
      "Prioritize testing by risk — spend the most effort where failure would hurt the most.",
      "Keep a traceability link between requirements and the tests that cover them.",
    ],
    summaryPoints: [
      "Testing evaluates software against expectations to find defects, not to achieve an impossible zero-defect guarantee.",
      "Testing is cheapest and most effective the earlier it starts in the lifecycle.",
      "Risk-based thinking, not exhaustive coverage, is what makes testing practical.",
    ],
    references: [{ label: "ISTQB Glossary — Testing", url: "https://glossary.istqb.org/en/search/testing" }],
    interviewQuestionIds: ["iq-fresher-1", "iq-fresher-2"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-sdlc",
    moduleId: "manual-testing",
    slug: "sdlc-software-development-life-cycle",
    title: "SDLC — Software Development Life Cycle",
    summary: "The stages software goes through from an idea to a maintained production system.",
    readingTimeMin: 7,
    definition:
      "SDLC (Software Development Life Cycle) is the structured process a team follows to plan, build, test, deliver, and maintain software.",
    explanation: [
      "Every SDLC model covers the same core stages — Requirement Analysis, Design, Implementation (coding), Testing, Deployment, and Maintenance — but differs in how rigidly and in what order those stages happen.",
      "Waterfall runs each stage once, sequentially: you finish requirements before design, finish design before coding, and so on. It's predictable but unforgiving of changing requirements, since testing only happens at the end.",
      "Agile (Scrum, Kanban) runs all stages repeatedly in short cycles (sprints), so working, tested software ships every 1-4 weeks. This surfaces defects and misunderstandings early, at the cost of needing continuous collaboration rather than a single upfront plan.",
      "V-Model pairs each development stage with a corresponding testing stage planned at the same time — e.g. requirements are written alongside the acceptance tests that will verify them. This is Waterfall's structure with testing built in from the start rather than bolted on at the end.",
    ],
    examples: [],
    advantages: [
      "Gives a shared vocabulary and checkpoint structure for planning, staffing, and tracking a project.",
      "Choosing the right model (Waterfall vs Agile vs V-Model) lets a team match process rigor to how well-understood and how volatile the requirements are.",
    ],
    disadvantages: [
      "A poor model-fit causes real pain: Waterfall on a fast-changing product wastes work on stale requirements; Agile without discipline can drift without ever locking down what 'done' means.",
    ],
    diagrams: [
      { title: "Waterfall SDLC", code: "flowchart TD\n  A[Requirements] --> B[Design]\n  B --> C[Implementation]\n  C --> D[Testing]\n  D --> E[Deployment]\n  E --> F[Maintenance]" },
      { title: "V-Model", code: "flowchart LR\n  subgraph Left[\"Development (left side)\"]\n  A[Requirements] --> B[System Design]\n  B --> C[Architecture Design]\n  C --> D[Module Design]\n  end\n  subgraph Right[\"Testing (right side)\"]\n  H[UAT] --> G[System Testing]\n  G --> F[Integration Testing]\n  F --> E[Unit Testing]\n  end\n  D --> Coding --> E\n  A -.maps to.-> H\n  B -.maps to.-> G\n  C -.maps to.-> F" },
    ],
    commonMistakes: [
      "Picking a model because it's familiar, not because it fits the project's rate of change.",
      "Running 'Agile' in name only — short iterations without actually shipping tested, working software each sprint.",
    ],
    bestPractices: [
      "In the V-Model, write test cases from requirements as soon as requirements are frozen — don't wait for code.",
      "In Agile, keep a Definition of Done that includes 'tested', not just 'coded'.",
    ],
    summaryPoints: [
      "SDLC = Requirements → Design → Implementation → Testing → Deployment → Maintenance, repeated or sequential depending on the model.",
      "Waterfall is sequential and predictable but rigid; Agile is iterative and adaptive but needs discipline; V-Model bakes testing planning into every development stage.",
    ],
    references: [{ label: "ISTQB Glossary — SDLC models", url: "https://glossary.istqb.org/en/search/" }],
    interviewQuestionIds: ["iq-fresher-3"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-stlc",
    moduleId: "manual-testing",
    slug: "stlc-software-testing-life-cycle",
    title: "STLC — Software Testing Life Cycle",
    summary: "The testing-specific phases nested inside the SDLC, from requirement analysis to closure.",
    readingTimeMin: 6,
    definition:
      "STLC (Software Testing Life Cycle) is the sequence of phases carried out specifically by the QA team within each release, to plan, design, execute, and close out testing.",
    explanation: [
      "STLC runs in parallel with, and is driven by, the SDLC — but it's the tester's own zoomed-in view of what happens during the 'Testing' stage (and, ideally, earlier).",
      "Requirement Analysis: testers study requirements to find what's testable, ambiguous, or missing — and raise questions before writing a single test case.",
      "Test Planning: a Test Lead defines scope, approach, resources, schedule, and entry/exit criteria — usually captured in a Test Plan document.",
      "Test Case Development: testers write test cases and test data, then get them reviewed.",
      "Environment Setup: the test environment (hardware, software, network, test data) is configured and verified with a smoke test.",
      "Test Execution: testers run the test cases, log results, and raise defects for failures — then re-test once fixes land.",
      "Test Closure: the team evaluates exit criteria, documents lessons learned, and archives test artifacts for the next cycle.",
    ],
    examples: [],
    advantages: [
      "Gives testing the same structured rigor development already gets, instead of ad hoc 'click around and see' testing.",
      "Entry/exit criteria per phase stop teams from silently skipping steps under deadline pressure.",
    ],
    disadvantages: ["Adds documentation overhead that can feel heavy on very small or fast-moving teams if applied too literally."],
    diagrams: [
      { title: "STLC phases", code: "flowchart LR\n  A[Requirement\\nAnalysis] --> B[Test\\nPlanning]\n  B --> C[Test Case\\nDevelopment]\n  C --> D[Environment\\nSetup]\n  D --> E[Test\\nExecution]\n  E --> F[Test\\nClosure]" },
    ],
    commonMistakes: ["Starting test case development before requirements are actually stable, causing constant rework.", "Skipping environment smoke-testing and losing a day of execution to broken test data."],
    bestPractices: ["Write entry and exit criteria for every phase up front, not after problems appear.", "Keep a Requirements Traceability Matrix (RTM) linking requirements to test cases as you go."],
    summaryPoints: ["STLC = Requirement Analysis → Test Planning → Test Case Development → Environment Setup → Test Execution → Test Closure.", "It's the QA-specific process nested inside the broader SDLC."],
    references: [{ label: "ISTQB Glossary — Test process", url: "https://glossary.istqb.org/en/search/test%20process" }],
    interviewQuestionIds: ["iq-fresher-4"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-testing-principles",
    moduleId: "manual-testing",
    slug: "seven-testing-principles",
    title: "The Seven Principles of Testing",
    summary: "The ISTQB foundation principles that explain why testing works the way it does.",
    readingTimeMin: 6,
    definition:
      "The seven testing principles are widely-accepted guidelines (formalized by ISTQB) that describe the fundamental nature and limits of software testing.",
    explanation: [
      "1. Testing shows the presence of defects, not their absence. Passing tests reduce risk; they never prove a system is bug-free.",
      "2. Exhaustive testing is impossible. Except for trivial cases, there are too many input combinations, paths, and timing scenarios to test all of them — so testing must be prioritized by risk.",
      "3. Early testing saves time and money. The earlier a defect is introduced-and-found in the same stage, the cheaper it is to fix (see Introduction to Software Testing for the cost curve).",
      "4. Defects cluster together. In practice, a small number of modules usually contain most of the defects (a Pareto-like distribution) — so testing effort should follow the history of where bugs tend to live.",
      "5. Beware the pesticide paradox. Running the same tests repeatedly stops finding new bugs, just like an insect population becomes resistant to a repeated pesticide — test cases need to be reviewed and updated regularly.",
      "6. Testing is context dependent. A banking app and a marketing landing page are tested very differently — approach, depth, and tooling should match the domain and its risk profile.",
      "7. Absence-of-errors is a fallacy. Finding and fixing every known bug is meaningless if the product still doesn't meet user needs — a bug-free product that solves the wrong problem still fails.",
    ],
    examples: [],
    advantages: ["Gives a shared, defensible rationale for decisions like risk-based prioritization or why a 'fully tested' release is still not risk-free."],
    disadvantages: [],
    diagrams: [],
    commonMistakes: [
      "Running the exact same regression suite for years without ever adding new cases (pesticide paradox).",
      "Chasing 100% test coverage as if it were achievable or, on its own, meaningful.",
    ],
    bestPractices: ["Periodically retire, refresh, or add to a regression suite instead of freezing it.", "Use defect clustering data (which modules produce the most bugs) to steer exploratory testing time."],
    summaryPoints: ["The 7 principles: defects not their absence, exhaustive testing is impossible, early testing pays off, defect clustering, pesticide paradox, context-dependent testing, absence-of-errors fallacy."],
    references: [{ label: "ISTQB Foundation Level Syllabus", url: "https://www.istqb.org/" }],
    interviewQuestionIds: ["iq-fresher-5"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-verification-validation",
    moduleId: "manual-testing",
    slug: "verification-vs-validation",
    title: "Verification vs Validation",
    summary: "Are we building the product right, versus are we building the right product.",
    readingTimeMin: 5,
    definition:
      "Verification checks whether a work product (requirements, design, code) conforms to its specification. Validation checks whether the finished product actually meets the user's real needs.",
    explanation: [
      "Verification is often summarized as 'Are we building the product right?' — it's about conformance to a spec, and it happens through static techniques: reviews, walkthroughs, inspections, and static analysis, without executing the code.",
      "Validation is 'Are we building the right product?' — it's about whether the software solves the actual user problem, and it happens through dynamic techniques: actually running the software (functional testing, UAT).",
      "A system can pass verification and still fail validation: code can perfectly match a spec that itself describes the wrong feature.",
    ],
    examples: [
      { language: "text", caption: "Side-by-side", code: "Verification                      Validation\n-------------------------------   -------------------------------\nAre we building it right?         Are we building the right thing?\nStatic (no code execution)        Dynamic (code is executed)\nReviews, walkthroughs, audits     Functional/UAT testing\nChecks against the spec           Checks against user needs" },
    ],
    advantages: ["Doing both catches two different classes of failure: 'built wrong' and 'built the wrong thing'."],
    disadvantages: [],
    diagrams: [],
    commonMistakes: ["Treating a passed code review as equivalent to the feature actually being useful or correct for the user.", "Skipping verification entirely and relying only on late-stage validation, which finds spec-level mistakes far too late."],
    bestPractices: ["Verify early and often (requirement reviews, design reviews, code reviews) — it's far cheaper than validation failures found near release."],
    summaryPoints: ["Verification = conformance to spec, static, 'right way'. Validation = fitness for user need, dynamic, 'right thing'. You need both."],
    references: [{ label: "ISTQB Glossary — Verification / Validation", url: "https://glossary.istqb.org/en/search/verification" }],
    interviewQuestionIds: ["iq-fresher-6"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-qa-vs-qc",
    moduleId: "manual-testing",
    slug: "qa-vs-qc-vs-testing",
    title: "QA vs QC vs Testing",
    summary: "Three related terms that get used interchangeably but describe different scopes of work.",
    readingTimeMin: 5,
    definition:
      "Quality Assurance (QA) is process-focused and preventive — it's about building quality INTO how the team works. Quality Control (QC) is product-focused and detective — it's about verifying the OUTPUT meets standards. Testing is one specific QC activity: executing software to find defects.",
    explanation: [
      "QA sits at the process level: defining coding standards, review checklists, and development methodology so that defects are less likely to be introduced in the first place. QA is everyone's job, not just testers'.",
      "QC sits at the product level: inspecting and measuring the actual deliverable against requirements. Testing is the most common QC activity in software, but QC also includes things like code reviews and static analysis of the finished artifact.",
      "In short: QA prevents defects by improving the process; QC (via testing) detects defects that got through anyway.",
    ],
    examples: [],
    advantages: ["Separating the concepts clarifies who owns what — a Scrum Master or Team Lead often owns QA process improvements, while testers execute QC/testing activities."],
    disadvantages: [],
    diagrams: [],
    commonMistakes: ["Calling every tester a 'QA' when their actual daily work is QC (testing the product) rather than process improvement.", "Assuming that if QC (testing) finds few bugs, QA (the process) must be excellent — testing coverage gaps can hide process problems just as easily."],
    bestPractices: ["Track process metrics (review effectiveness, defect leakage by phase) as genuine QA signals, not just test-pass-rate as a proxy for everything."],
    summaryPoints: ["QA = process, preventive, everyone's responsibility. QC = product, detective, usually the QA/test team's responsibility. Testing = the primary technique used to do QC."],
    references: [{ label: "ISTQB Glossary — Quality assurance", url: "https://glossary.istqb.org/en/search/quality%20assurance" }],
    interviewQuestionIds: ["iq-fresher-7"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-defect-lifecycle",
    moduleId: "manual-testing",
    slug: "defect-lifecycle",
    title: "Defect Life Cycle (Bug Life Cycle)",
    summary: "The states a bug moves through from discovery to closure, and who's responsible at each step.",
    readingTimeMin: 7,
    definition:
      "The Defect Life Cycle (or Bug Life Cycle) is the sequence of states a defect passes through, from the moment it's logged by a tester to the moment it's closed.",
    explanation: [
      "New: a tester logs a defect for the first time, with steps to reproduce, expected vs actual result, environment, and severity/priority.",
      "Assigned: a Test/Dev Lead reviews the defect and assigns it to a developer.",
      "Open / In Progress: the developer investigates and works on a fix.",
      "Fixed: the developer has made a code change and believes the issue is resolved; it moves back to the tester.",
      "Retest: the tester re-executes the original steps against the fix.",
      "Verified / Closed: if the fix works, the defect is marked Verified then Closed. If not, it's Reopened and sent back to Assigned/Open.",
      "Along the way a defect can also be marked Duplicate (already logged elsewhere), Rejected (not actually a bug, e.g. working as designed), or Deferred (valid, but postponed to a later release).",
    ],
    examples: [],
    advantages: ["A consistent lifecycle keeps everyone — testers, developers, leads — aligned on what state a bug is in and whose turn it is to act."],
    disadvantages: [],
    diagrams: [
      { title: "Defect life cycle", code: "stateDiagram-v2\n  [*] --> New\n  New --> Assigned\n  Assigned --> Open\n  Open --> Fixed\n  Fixed --> Retest\n  Retest --> Verified: pass\n  Retest --> Reopened: fail\n  Reopened --> Open\n  Verified --> Closed\n  New --> Rejected\n  New --> Duplicate\n  Open --> Deferred" },
    ],
    commonMistakes: ["Closing a defect straight from 'Fixed' without an independent Retest step.", "Vague repro steps that force the developer to guess, wasting a full round trip through the cycle."],
    bestPractices: ["Always include exact steps to reproduce, expected vs actual behavior, environment, and evidence (screenshot/log) when logging a defect.", "Re-verify on the same environment/build combination the bug was originally found on."],
    summaryPoints: ["Core flow: New → Assigned → Open → Fixed → Retest → Verified → Closed, with Reopened, Rejected, Duplicate, and Deferred as branch states."],
    references: [{ label: "ISTQB Glossary — Defect", url: "https://glossary.istqb.org/en/search/defect" }],
    interviewQuestionIds: ["iq-fresher-8", "iq-fresher-9"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-severity-priority",
    moduleId: "manual-testing",
    slug: "severity-vs-priority",
    title: "Severity vs Priority",
    summary: "How bad a bug is, versus how soon it needs to be fixed — two independent axes.",
    readingTimeMin: 5,
    definition:
      "Severity measures the technical impact of a defect on the system's functionality. Priority measures the urgency of fixing it relative to business needs. They are independent — one does not determine the other.",
    explanation: [
      "Severity is set by the tester based on what breaks: does the app crash (critical), does a major feature fail (high), does a minor feature misbehave (medium), or is it cosmetic (low)?",
      "Priority is usually set by the Test/Product Lead based on business impact and timing: should this be fixed immediately, in this release, in the next release, or whenever convenient?",
      "The classic interview example: a spelling mistake in the company name on the homepage is LOW severity (nothing is broken functionally) but can be HIGH priority (brand damage, fix before anyone else sees it). Conversely, a crash in a rarely-used admin report might be HIGH severity but LOW priority if almost no one hits that path.",
    ],
    examples: [
      { language: "text", caption: "Four quadrants", code: "High Severity + High Priority: Payment fails for all users — fix now\nHigh Severity + Low Priority:  Crash in a rarely-used legacy report\nLow Severity + High Priority:  Wrong logo/typo on the homepage\nLow Severity + Low Priority:   Minor spacing issue on a settings page" },
    ],
    advantages: ["Separating the two lets triage happen faster and more objectively — testers report severity from the system's perspective, business owners set priority from the customer/market perspective."],
    disadvantages: [],
    diagrams: [],
    commonMistakes: ["Assuming severity and priority always move together — most real backlogs have plenty of high-severity/low-priority and low-severity/high-priority tickets.", "Letting the tester unilaterally decide priority, when it's really a business call."],
    bestPractices: ["Set severity as objectively as possible from technical impact alone; leave priority to whoever owns the release/business tradeoffs."],
    summaryPoints: ["Severity = technical impact (tester's call). Priority = fix urgency (business call). They're independent axes, not two words for the same thing."],
    references: [{ label: "ISTQB Glossary — Severity", url: "https://glossary.istqb.org/en/search/severity" }],
    interviewQuestionIds: ["iq-fresher-10"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-smoke-sanity-regression",
    moduleId: "manual-testing",
    slug: "smoke-sanity-regression-testing",
    title: "Smoke, Sanity, and Regression Testing",
    summary: "Three testing types that get confused constantly — when to run each and why.",
    readingTimeMin: 6,
    definition:
      "Smoke testing verifies a new build is stable enough to test further. Sanity testing verifies a specific fix or small change works as expected. Regression testing verifies that recent changes haven't broken previously working functionality.",
    explanation: [
      "Smoke testing runs first, on every new build, and is shallow-but-wide: does the app launch, can you log in, does the main navigation work? If smoke tests fail, the build is rejected and sent back to development without deeper testing wasted on it.",
      "Sanity testing is narrow-but-deep: after a specific bug fix or small feature tweak, you test just that area (and its immediate neighbors) rationally/quickly to confirm the change works, without a full regression pass.",
      "Regression testing is the broadest: re-running a wider suite of existing test cases (often automated) after any change, to catch unintended side effects anywhere in the system — not just near the change itself.",
    ],
    examples: [
      { language: "text", caption: "When each runs", code: "New build deployed        -> Smoke test (build accept/reject gate)\nOne bug just got fixed    -> Sanity test (quick, narrow check)\nBefore a release ships    -> Regression test (broad safety net)" },
    ],
    advantages: ["Running them in the right order (smoke -> sanity -> regression) avoids wasting deep-testing effort on a fundamentally broken build."],
    disadvantages: [],
    diagrams: [{ title: "Order of operations", code: "flowchart LR\n  A[New Build] --> B{Smoke Test\\nPasses?}\n  B -- No --> R[Reject Build]\n  B -- Yes --> C[Sanity Test\\non the change]\n  C --> D[Regression Test\\nbefore release]" }],
    commonMistakes: ["Using 'smoke test' and 'sanity test' interchangeably in conversation, which causes confusion about scope.", "Skipping regression testing on 'small' changes — small changes cause a large share of real production regressions precisely because they're under-tested."],
    bestPractices: ["Automate smoke and regression suites first — they run on every build and provide the most repeated value.", "Keep sanity checks manual and fast; they're meant to be quick, targeted confirmations, not full suites."],
    summaryPoints: ["Smoke = is the build stable enough to test? Sanity = does this specific fix work? Regression = did anything else break?"],
    references: [{ label: "ISTQB Glossary — Regression testing", url: "https://glossary.istqb.org/en/search/regression%20testing" }],
    interviewQuestionIds: ["iq-fresher-11"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
  {
    id: "mt-black-white-grey-box",
    moduleId: "manual-testing",
    slug: "black-box-white-box-grey-box-testing",
    title: "Black Box, White Box, and Grey Box Testing",
    summary: "Three testing approaches defined by how much internal knowledge the tester has.",
    readingTimeMin: 6,
    definition:
      "Black box testing evaluates a system purely through its inputs and outputs, with no knowledge of internal code. White box testing examines and tests the internal code structure directly. Grey box testing is a blend — the tester has partial internal knowledge (e.g. of the database schema or API contracts) while still testing mostly from the outside.",
    explanation: [
      "Black box testing is done from the user's perspective: given an input, is the output correct? It doesn't require programming knowledge, and techniques like equivalence partitioning and boundary value analysis live here. Most manual functional testing is black box.",
      "White box testing requires reading and understanding the source code — techniques include statement coverage, branch coverage, and path coverage. This is typically done by developers or SDETs writing unit tests, not by manual testers.",
      "Grey box testing sits in between: a tester might know the database schema well enough to check data integrity directly, or know the API contract well enough to craft more targeted black-box UI tests — without reading the application's internal implementation code.",
    ],
    examples: [
      { language: "text", caption: "Who typically does each", code: "Black Box: Manual/Functional testers, based on requirements\nWhite Box: Developers, via unit tests and code coverage tools\nGrey Box:  SDETs / testers with schema or API knowledge" },
    ],
    advantages: ["Different levels of internal visibility catch different bug classes — black box catches user-facing failures, white box catches internal logic errors invisible from the UI."],
    disadvantages: [],
    diagrams: [],
    commonMistakes: ["Assuming black box testing is 'less skilled' than white box — designing a good black-box test suite (equivalence classes, boundaries, negative cases) is a distinct, real skill."],
    bestPractices: ["Use white box coverage (branch/statement) as a developer-side quality gate, and black box test design (equivalence partitioning, boundary values) as the tester-side quality gate — don't rely on just one."],
    summaryPoints: ["Black box = no code knowledge, tests via inputs/outputs. White box = full code knowledge, tests internal logic/paths. Grey box = partial internal knowledge (schema/API) combined with external testing."],
    references: [{ label: "ISTQB Glossary — Black-box testing", url: "https://glossary.istqb.org/en/search/black-box%20testing" }],
    interviewQuestionIds: ["iq-fresher-12"],
    quizId: "quiz-manual-testing-basics",
    flashcardSetId: "fc-manual-testing-basics",
  },
];

export const MANUAL_TESTING_QUIZ: Quiz = {
  id: "quiz-manual-testing-basics",
  moduleId: "manual-testing",
  title: "Manual Testing Fundamentals",
  questions: [
    {
      id: "q1",
      question: "According to the testing principles, what does passing a set of tests tell you?",
      options: ["The software has no defects", "The software is ready to ship", "Testing has not found defects with the tests run so far", "The requirements were correct"],
      correctIndex: 2,
      explanation: "Testing shows the presence of defects, not their absence. Passing tests only means those specific tests didn't find a problem.",
    },
    {
      id: "q2",
      question: "Which SDLC model pairs each development stage with a corresponding testing stage planned at the same time?",
      options: ["Waterfall", "V-Model", "Spiral", "Agile"],
      correctIndex: 1,
      explanation: "The V-Model plans, for example, acceptance tests alongside requirements and system tests alongside system design.",
    },
    {
      id: "q3",
      question: "In STLC, when should test case development ideally begin?",
      options: ["After test execution starts", "After the environment is set up", "Once requirements are analyzed and stable", "After the defect life cycle closes"],
      correctIndex: 2,
      explanation: "Test Case Development follows Requirement Analysis and Test Planning in STLC.",
    },
    {
      id: "q4",
      question: "The 'pesticide paradox' warns testers about what?",
      options: ["Running the same tests repeatedly stops finding new bugs over time", "Testing too many edge cases wastes time", "Automated tests are less reliable than manual ones", "Bugs cluster in a small number of modules"],
      correctIndex: 0,
      explanation: "Just like pests become resistant to a repeated pesticide, unchanged test suites stop revealing new defects — they need to be reviewed and updated.",
    },
    {
      id: "q5",
      question: "Which best describes Validation?",
      options: ["Checking code against the design document", "Checking whether the built product meets actual user needs", "A static review with no code execution", "Verifying a defect fix in isolation"],
      correctIndex: 1,
      explanation: "Validation asks 'are we building the right product?' and is done dynamically, by actually running the software.",
    },
    {
      id: "q6",
      question: "A homepage has a typo in the company name but nothing is functionally broken. How would this typically be classified?",
      options: ["High severity, high priority", "High severity, low priority", "Low severity, high priority", "Low severity, low priority"],
      correctIndex: 2,
      explanation: "Nothing is functionally broken (low severity) but brand damage means it should be fixed fast (high priority) — the classic example of severity and priority diverging.",
    },
    {
      id: "q7",
      question: "After a developer fixes a bug and a tester confirms it, but a build later needs to check nothing else broke as a result, what type of testing is that final broad check?",
      options: ["Smoke testing", "Sanity testing", "Regression testing", "Exploratory testing"],
      correctIndex: 2,
      explanation: "Regression testing is the broad re-run of existing tests to catch unintended side effects anywhere in the system, not just near the fix.",
    },
    {
      id: "q8",
      question: "Which testing approach requires reading and understanding the application's source code?",
      options: ["Black box testing", "White box testing", "Grey box testing", "None of these require code knowledge"],
      correctIndex: 1,
      explanation: "White box testing examines and tests internal code structure directly (statement/branch/path coverage), unlike black or grey box testing.",
    },
  ],
};

export const MANUAL_TESTING_FLASHCARDS: FlashcardSet = {
  id: "fc-manual-testing-basics",
  moduleId: "manual-testing",
  title: "Manual Testing Fundamentals",
  cards: [
    { id: "c1", front: "Testing shows the presence of defects, not their...", back: "Absence. Passing tests reduce risk; they never prove zero defects." },
    { id: "c2", front: "SDLC stands for", back: "Software Development Life Cycle — Requirements → Design → Implementation → Testing → Deployment → Maintenance." },
    { id: "c3", front: "STLC stands for", back: "Software Testing Life Cycle — Requirement Analysis → Test Planning → Test Case Development → Environment Setup → Test Execution → Test Closure." },
    { id: "c4", front: "Verification asks...", back: "'Are we building the product right?' — static conformance to spec (reviews, walkthroughs)." },
    { id: "c5", front: "Validation asks...", back: "'Are we building the right product?' — dynamic testing against real user needs." },
    { id: "c6", front: "QA is...", back: "Process-focused and preventive. Improving how the team works so defects are less likely." },
    { id: "c7", front: "QC is...", back: "Product-focused and detective. Inspecting the actual deliverable — testing is the main QC activity." },
    { id: "c8", front: "Severity measures...", back: "Technical impact of a defect on the system. Set by the tester." },
    { id: "c9", front: "Priority measures...", back: "Business urgency of fixing a defect. Usually set by the lead/product owner." },
    { id: "c10", front: "Smoke testing checks...", back: "Whether a new build is stable enough to test further — shallow but wide." },
    { id: "c11", front: "Sanity testing checks...", back: "A specific fix or small change works — narrow but deep, quick." },
    { id: "c12", front: "Regression testing checks...", back: "That recent changes haven't broken previously working functionality — broad safety net." },
    { id: "c13", front: "Black box testing", back: "Tests via inputs/outputs only, no code knowledge required." },
    { id: "c14", front: "White box testing", back: "Tests internal code structure directly — statement/branch/path coverage." },
    { id: "c15", front: "The 'pesticide paradox'", back: "Repeating the same tests stops finding new bugs over time — refresh your suite." },
  ],
};
