import { uid } from "./id";
import type { PortfolioContent } from "./types";

export function createSampleContent(): PortfolioContent {
  return {
    profile: {
      name: "Antony Joshua S",
      role: "Quality Analyst",
      tagline:
        "3+ years building defect-free software across web, mobile, VR, and AI platforms. Passionate about quality, precision, and catching bugs before users do.",
      location: "Chennai, India",
      email: "antonyjoshua413@gmail.com",
      phone: "+91 95140 84222",
      github: "https://github.com/Antonyjoshua",
      linkedin: "https://linkedin.com/in/antony-joshua-471704aj",
      resumeAttachmentId: null,
      photoAttachmentId: null,
    },
    stats: [
      { id: uid(), value: "2500", suffix: "+", label: "Defects Found" },
      { id: uid(), value: "3", suffix: "+", label: "Years Experience" },
      { id: uid(), value: "9", suffix: "+", label: "Projects Delivered" },
      { id: uid(), value: "8", suffix: "", label: "Domains Covered" },
    ],
    aboutParagraphs: [
      "I'm a Quality Analyst with 3+ years of experience delivering defect-free software. With hands-on experience across web, mobile (iOS/Android), VR, and AI platforms, I've worked in diverse domains including EdTech, healthcare, finance, entertainment, and e-commerce.",
      "I specialize in designing and executing test strategies that catch issues early, collaborate closely with developers and product owners, and adapt quickly to dynamic Agile environments. From validating cutting-edge EEG hardware integrations to testing RAG and ML models, I bring thoroughness and technical curiosity to every project — having identified and reported 2500+ defects across UI, functional, API, integration, streaming, and production-impacting issues, all tracked in JIRA.",
    ],
    education: [
      { id: uid(), degree: "MCA — Master of Computer Applications", institution: "Madras University", status: "Pursuing", note: "" },
      { id: uid(), degree: "BCA — Bachelor of Computer Applications", institution: "Jaya College of Arts & Science", status: "", note: "85%" },
    ],
    contactDetails: [
      { id: uid(), label: "Location", value: "Chennai, India", link: "" },
      { id: uid(), label: "Email", value: "antonyjoshua413@gmail.com", link: "mailto:antonyjoshua413@gmail.com" },
      { id: uid(), label: "Phone", value: "+91 95140 84222", link: "tel:+919514084222" },
      { id: uid(), label: "LinkedIn", value: "antony-joshua-471704aj", link: "https://linkedin.com/in/antony-joshua-471704aj" },
    ],
    passions: [
      { id: uid(), icon: "🧪", title: "Automation Engineering", desc: "Building Playwright + TypeScript frameworks with parallel execution, rich reporting, and CI/CD integration." },
      { id: uid(), icon: "🤖", title: "AI-Driven Testing", desc: "Applying LLMs to root cause analysis, automatic test failure explanation, and intelligent bug triage." },
      { id: uid(), icon: "🔍", title: "Precision Bug Analysis", desc: "Identifying critical defects in web, mobile, VR, and AI platforms before they reach production." },
      { id: uid(), icon: "🛠️", title: "Developer Tooling", desc: "Crafting QA utilities and internal tools that multiply team velocity without sacrificing quality." },
      { id: uid(), icon: "📱", title: "Cross-Platform Testing", desc: "Ensuring flawless experiences across browsers, devices, operating systems, and viewport sizes." },
      { id: uid(), icon: "🚀", title: "Future-Ready QA", desc: "Designing test strategies for next-gen platforms — AI systems, VR environments, and edge cases that don't exist yet." },
    ],
    skills: [
      { id: uid(), category: "Test Automation", icon: "⚙️", items: ["Playwright", "Selenium WebDriver", "TestNG", "Cucumber"] },
      { id: uid(), category: "Programming", icon: "💻", items: ["TypeScript", "Java"] },
      { id: uid(), category: "CI/CD & DevOps", icon: "🔧", items: ["Jenkins", "Maven", "GitHub", "SonarQube"] },
      { id: uid(), category: "Testing Types", icon: "🔬", items: ["Functional Testing", "Regression Testing", "UI/UX Testing", "AI / RAG Testing", "ML Model Testing", "API Testing"] },
      { id: uid(), category: "Databases", icon: "🗄️", items: ["SQL", "MongoDB"] },
      { id: uid(), category: "Tools & Platforms", icon: "📋", items: ["JIRA", "Postman", "Web", "Mobile (iOS/Android)", "VR"] },
      { id: uid(), category: "Methodologies", icon: "🔄", items: ["Agile / Scrum", "SDLC", "STLC"] },
    ],
    experience: [
      {
        id: uid(),
        company: "Scope Thinkers",
        role: "Quality Analyst",
        period: "Dec 2025 – Present",
        current: true,
        highlights: [
          "Performing manual and automation testing across EdTech and Entertainment domains.",
          "Building and maintaining end-to-end automation test suites using Playwright with TypeScript.",
          "Tested web, Android, and iOS platforms for Jeshwar Teaching — a live streaming & e-learning platform.",
          "Validated point purchase/redemption, franchise management, and loyalty workflows for Funtown Kids Park.",
        ],
        tech: ["Playwright", "TypeScript", "Manual Testing", "Web", "Android", "iOS", "Agile"],
      },
      {
        id: uid(),
        company: "NITInnov Technologies Private Limited",
        role: "Software Tester",
        period: "Jun 2024 – Sep 2025",
        current: false,
        highlights: [
          "Performed manual testing on VR-based healthcare platform (ConfidentoAI) across VR, web, and mobile (iOS/Android) modules.",
          "Validated Muse EEG device integration, ensuring accurate data capture within the app.",
          "Tested RAG and machine learning models, assisting in the design and validation of prompt templates.",
          "Designed and executed detailed manual test cases, logging and tracking defects in Agile sprints.",
        ],
        tech: ["VR Testing", "Mobile Testing", "EEG Validation", "ML Model Testing", "Agile"],
      },
      {
        id: uid(),
        company: "Arkashya Tech Solution Pvt Ltd",
        role: "Software Tester",
        period: "Jul 2023 – May 2024",
        current: false,
        highlights: [
          "Designed and executed automation test scripts for web applications using Selenium + TestNG.",
          "Conducted manual test cases for functional and regression testing.",
          "Prepared detailed bug reports and assisted developers with root cause analysis.",
          "Collaborated with product owners and stakeholders to refine requirements in Agile sprints.",
        ],
        tech: ["Selenium", "TestNG", "Regression Testing", "Bug Reporting"],
      },
      {
        id: uid(),
        company: "Arkashya Tech Solution Pvt Ltd",
        role: "Software Tester — Intern",
        period: "Mar 2023 – Jun 2023",
        current: false,
        highlights: [
          "Assisted in manual testing of web and mobile applications.",
          "Created and executed basic test cases; logged and tracked defects.",
          "Gained exposure to SDLC, STLC, and defect life cycle processes.",
          "Developed introductory Selenium automation scripts.",
        ],
        tech: ["Manual Testing", "SDLC", "STLC", "Selenium"],
      },
      {
        id: uid(),
        company: "Sutherland Global Services",
        role: "Technical Support — SME",
        period: "Oct 2020 – Oct 2022",
        current: false,
        highlights: [
          "Delivered technical support to Amazon customers via phone, email, and chat.",
          "Part of the core launch team, supporting a wide range of Amazon.com products.",
          "Promoted to Team Lead for 10 months, managing operations and mentoring team members.",
          "Recognized with 2x RnR Awards for consistent performance and service excellence.",
        ],
        tech: ["Team Lead", "Technical Support", "Amazon", "2x RnR Award"],
      },
    ],
    projects: [
      { id: uid(), title: "Jeshwar Teaching", subtitle: "EdTech · Education Technology", company: "Scope Thinkers", description: "Tested a full-stack EdTech platform covering live classes, video streaming, digital content management, online book store, and e-learning modules. Validated Web, Android, and iOS applications across all sub-domains including live coaching, content delivery, and e-commerce workflows.", tags: ["Playwright", "TypeScript", "Live Streaming", "iOS", "Android", "E-Commerce"], liveUrl: "", githubUrl: "", status: "enterprise" },
      { id: uid(), title: "Funtown Kids Park", subtitle: "Entertainment · Recreation", company: "Scope Thinkers", description: "Validated an amusement park management platform including point purchase & redemption, play activity management, franchise management, customer management, and loyalty & rewards workflows. Tested both Android app and web portal end-to-end.", tags: ["Playwright", "TypeScript", "Android", "Loyalty Systems", "Franchise"], liveUrl: "", githubUrl: "", status: "enterprise" },
      { id: uid(), title: "Scope AI Chat", subtitle: "Artificial Intelligence · Generative AI", company: "Scope Thinkers", description: "Tested a domain-specific AI chatbot platform built on RAG architecture. Users upload documents and website links to generate an embeddable widget. Validated context-aware responses, multi-source data ingestion, document processing pipelines, and widget integration into external apps.", tags: ["RAG", "Generative AI", "Playwright", "TypeScript", "SaaS", "Knowledge Retrieval"], liveUrl: "", githubUrl: "", status: "live" },
      { id: uid(), title: "Scope Employee Portal", subtitle: "HRMS · Human Resource Management", company: "Scope Thinkers", description: "Validated an HRMS platform covering employee information management, attendance tracking, leave management, and HR operational workflows. Tested both web and mobile applications for seamless employee lifecycle management.", tags: ["Playwright", "TypeScript", "Mobile", "Web", "HR Automation"], liveUrl: "", githubUrl: "", status: "enterprise" },
      { id: uid(), title: "ConfidentoAI", subtitle: "Healthcare · VR", company: "NITInnov Technologies", description: "Led manual testing across web, mobile, and VR platforms for a VR-based healthcare solution. Validated Muse EEG device integration, tested RAG and ML models, and managed defects in Agile sprints.", tags: ["VR", "EEG", "ML Testing", "RAG", "Agile"], liveUrl: "", githubUrl: "", status: "enterprise" },
      { id: uid(), title: "Cornovus Capital", subtitle: "Finance · Real Estate", company: "NITInnov Technologies", description: "Performed functional and regression testing for commercial real estate loan workflows. Validated loan input forms and confirmed accurate loan calculations for buyer's equity, term length, and interest rates.", tags: ["Functional Testing", "Regression", "Finance"], liveUrl: "", githubUrl: "", status: "enterprise" },
      { id: uid(), title: "MyHotel AI", subtitle: "Hospitality · PMS", company: "Arkashya Tech Solution", description: "Performed functional, regression, and UI testing on web, Android, and iOS platforms. Executed automation test scripts for web using Selenium + TestNG.", tags: ["Selenium", "TestNG", "iOS", "Android"], liveUrl: "", githubUrl: "", status: "enterprise" },
      { id: uid(), title: "Zane Hospitality", subtitle: "E-commerce", company: "NITInnov Technologies", description: "Tested web modules for product listings, order placement, and customer inquiry workflows. Ensured seamless user experience across all critical e-commerce flows.", tags: ["Web Testing", "UI/UX", "E-commerce"], liveUrl: "", githubUrl: "", status: "enterprise" },
      { id: uid(), title: "ACW Card", subtitle: "NFC Technology", company: "Arkashya Tech Solution", description: "Conducted cross-device NFC testing for a smart digital business card application. Validated interactions and compatibility, ensuring smooth app performance across devices.", tags: ["NFC Testing", "Cross-device", "Compatibility"], liveUrl: "", githubUrl: "", status: "live" },
    ],
    certifications: [
      { id: uid(), title: "Selenium WebDriver with Java", subtitle: "Basics to Advanced + Frameworks", issuer: "Udemy", date: "Oct 2024", instructor: "Rahul Shetty", duration: "55.5 hrs", skills: ["Selenium", "Java", "TestNG", "Frameworks"] },
      { id: uid(), title: "ML (AI) Testing", subtitle: "Introduction to Machine Learning Models Testing", issuer: "Udemy", date: "Dec 2024", instructor: "Rahul Shetty", duration: "5 hrs", skills: ["AI Testing", "ML Models", "QA Strategy"] },
      { id: uid(), title: "Master Class to QA Professionals", subtitle: "Certificate of Participation", issuer: "Testleaf", date: "Oct 2025", instructor: "Testleaf", duration: "", skills: ["QA Best Practices", "Test Strategy"] },
      { id: uid(), title: "Automation Testing Skills", subtitle: "Cracking QA Roles in Top Tech Companies — Webinar", issuer: "GUVI x HCL", date: "Nov 2025", instructor: "GUVI | HCL", duration: "", skills: ["Automation", "Interview Prep", "Career Growth"] },
    ],
    extras: [
      { id: uid(), icon: "🕹️", title: "AI Agents", desc: "Experimenting with autonomous testing agents that plan, execute, and report test scenarios without human intervention.", tag: "Live Experiment" },
      { id: uid(), icon: "🔌", title: "MCP Integration", desc: "Building Model Context Protocol adapters to give AI models real-time access to test results, logs, and CI/CD state.", tag: "In Progress" },
      { id: uid(), icon: "📝", title: "Prompt Engineering", desc: "Designing and testing prompts that reliably extract bug reproduction steps, severity, and fix suggestions from raw logs.", tag: "Live Experiment" },
      { id: uid(), icon: "🧠", title: "Smart Test Selection", desc: "ML-based test prioritization that predicts which test cases are most likely to catch regressions for a given code change.", tag: "Research" },
      { id: uid(), icon: "⚖️", title: "LLM Test Validation", desc: "Frameworks for evaluating LLM response accuracy, hallucination rate, and contextual relevance in production RAG systems.", tag: "Live Experiment" },
      { id: uid(), icon: "♾️", title: "Autonomous QA Pipeline", desc: "A self-healing test suite that detects flaky tests, auto-retries with different strategies, and reports anomalies intelligently.", tag: "In Progress" },
    ],
  };
}
