import type { ResumeTemplate, SectionType } from "../types";
import { buildTheme, FONT_STACKS } from "./theme-presets";

// A one-column, ATS-first section order shared by most single-column templates.
const SINGLE_COLUMN_ORDER: { type: SectionType; column: 0 | 1 }[] = [
  { type: "name", column: 0 },
  { type: "title", column: 0 },
  { type: "contact", column: 0 },
  { type: "summary", column: 0 },
  { type: "experience", column: 0 },
  { type: "education", column: 0 },
  { type: "skills", column: 0 },
  { type: "projects", column: 0 },
  { type: "certifications", column: 0 },
];

function twoColumnOrder(sidebarExtra: SectionType[] = []): { type: SectionType; column: 0 | 1 }[] {
  return [
    { type: "photo", column: 1 },
    { type: "name", column: 0 },
    { type: "title", column: 0 },
    { type: "summary", column: 0 },
    { type: "experience", column: 0 },
    { type: "projects", column: 0 },
    { type: "contact", column: 1 },
    { type: "skills", column: 1 },
    { type: "education", column: 1 },
    ...sidebarExtra.map((type) => ({ type, column: 1 as const })),
  ];
}

export const RESUME_TEMPLATES: ResumeTemplate[] = [
  {
    id: "ats-professional",
    name: "ATS Professional",
    category: "ATS Professional",
    description: "Pure single-column, no tables or graphics — built to parse cleanly in any applicant tracking system.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "a4", headerLayout: "stacked" },
    theme: buildTheme({ headingFont: FONT_STACKS.arial, bodyFont: FONT_STACKS.arial, primaryColor: "#111827", accentColor: "#1d4ed8", dividers: true }),
    sections: SINGLE_COLUMN_ORDER,
  },
  {
    id: "modern",
    name: "Modern",
    category: "Modern",
    description: "Clean sans-serif with a soft indigo accent — a versatile everyday resume.",
    atsFriendly: true,
    layout: { columns: 2, columnRatio: 0.68, pageSize: "a4", headerLayout: "banner" },
    theme: buildTheme({ headingFont: FONT_STACKS.segoe, bodyFont: FONT_STACKS.segoe, primaryColor: "#312e81", accentColor: "#6366f1", backgroundColor: "#fafafa" }),
    sections: twoColumnOrder(["languages", "interests"]),
  },
  {
    id: "executive",
    name: "Executive",
    category: "Executive",
    description: "Serif headings and a restrained gold accent for senior/leadership roles.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "letter", headerLayout: "stacked" },
    theme: buildTheme({ headingFont: FONT_STACKS.georgia, bodyFont: FONT_STACKS.times, primaryColor: "#1c1917", accentColor: "#a16207", fontSize: 13, sectionSpacing: 22 }),
    sections: SINGLE_COLUMN_ORDER,
  },
  {
    id: "minimal",
    name: "Minimal",
    category: "Minimal",
    description: "Black and white, no dividers, generous whitespace — content does the talking.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "a4", headerLayout: "stacked" },
    theme: buildTheme({ headingFont: FONT_STACKS.verdana, bodyFont: FONT_STACKS.verdana, primaryColor: "#000000", accentColor: "#000000", mutedColor: "#525252", dividers: false, sectionSpacing: 20 }),
    sections: SINGLE_COLUMN_ORDER,
  },
  {
    id: "corporate",
    name: "Corporate",
    category: "Corporate",
    description: "Navy and steel blue with a bordered header band for traditional enterprise roles.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "letter", headerLayout: "split" },
    theme: buildTheme({ headingFont: FONT_STACKS.calibri, bodyFont: FONT_STACKS.calibri, primaryColor: "#0c2d57", accentColor: "#3b6ea5", borders: true }),
    sections: SINGLE_COLUMN_ORDER,
  },
  {
    id: "software-engineer",
    name: "Software Engineer",
    category: "Software Engineer",
    description: "Slate and cyan, skills-forward layout with a dedicated projects section up top.",
    atsFriendly: true,
    layout: { columns: 2, columnRatio: 0.66, pageSize: "a4", headerLayout: "banner" },
    theme: buildTheme({ headingFont: FONT_STACKS.segoe, bodyFont: FONT_STACKS.segoe, primaryColor: "#0f172a", accentColor: "#0891b2" }),
    sections: twoColumnOrder(["certifications"]),
  },
  {
    id: "qa-engineer",
    name: "QA Engineer",
    category: "QA Engineer",
    description: "Teal and amber in QuanGrade's own IBM Plex Mono — built around test coverage and quality metrics.",
    atsFriendly: true,
    layout: { columns: 2, columnRatio: 0.66, pageSize: "a4", headerLayout: "banner" },
    theme: buildTheme({ headingFont: FONT_STACKS.plexMono, bodyFont: FONT_STACKS.arial, primaryColor: "#134e4a", accentColor: "#d97706" }),
    sections: twoColumnOrder(["certifications"]),
  },
  {
    id: "automation-tester",
    name: "Automation Tester",
    category: "Automation Tester",
    description: "A \"passing test\" green accent in monospace headings for framework-and-tooling-heavy résumés.",
    atsFriendly: true,
    layout: { columns: 2, columnRatio: 0.66, pageSize: "a4", headerLayout: "banner" },
    theme: buildTheme({ headingFont: FONT_STACKS.plexMono, bodyFont: FONT_STACKS.arial, primaryColor: "#14532d", accentColor: "#16a34a" }),
    sections: twoColumnOrder(["certifications"]),
  },
  {
    id: "playwright-tester",
    name: "Playwright Tester",
    category: "Playwright Tester",
    description: "Emerald and slate, monospace headings — for end-to-end/browser automation specialists.",
    atsFriendly: true,
    layout: { columns: 2, columnRatio: 0.66, pageSize: "a4", headerLayout: "banner" },
    theme: buildTheme({ headingFont: FONT_STACKS.plexMono, bodyFont: FONT_STACKS.arial, primaryColor: "#052e2b", accentColor: "#10b981" }),
    sections: twoColumnOrder(["languages"]),
  },
  {
    id: "devops",
    name: "DevOps",
    category: "DevOps",
    description: "Purple and orange — a CI/CD pipeline palette for infrastructure and release-engineering roles.",
    atsFriendly: true,
    layout: { columns: 2, columnRatio: 0.66, pageSize: "a4", headerLayout: "banner" },
    theme: buildTheme({ headingFont: FONT_STACKS.plexMono, bodyFont: FONT_STACKS.segoe, primaryColor: "#3b0764", accentColor: "#ea580c" }),
    sections: twoColumnOrder(["certifications"]),
  },
  {
    id: "ui-ux-designer",
    name: "UI/UX Designer",
    category: "UI/UX Designer",
    description: "Coral and violet with a photo and a portfolio-forward layout.",
    atsFriendly: false,
    layout: { columns: 2, columnRatio: 0.64, pageSize: "a4", headerLayout: "split" },
    theme: buildTheme({ headingFont: FONT_STACKS.trebuchet, bodyFont: FONT_STACKS.segoe, primaryColor: "#701a75", accentColor: "#f472b6", alignment: "left" }),
    sections: twoColumnOrder(["interests"]),
  },
  {
    id: "project-manager",
    name: "Project Manager",
    category: "Project Manager",
    description: "Blue and orange, milestone-style experience layout for delivery and program roles.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "letter", headerLayout: "split" },
    theme: buildTheme({ headingFont: FONT_STACKS.calibri, bodyFont: FONT_STACKS.calibri, primaryColor: "#1e3a8a", accentColor: "#ea580c" }),
    sections: SINGLE_COLUMN_ORDER,
  },
  {
    id: "business-analyst",
    name: "Business Analyst",
    category: "Business Analyst",
    description: "Navy and teal, structured and requirements-focused.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "letter", headerLayout: "stacked" },
    theme: buildTheme({ headingFont: FONT_STACKS.segoe, bodyFont: FONT_STACKS.segoe, primaryColor: "#0f3d3e", accentColor: "#0d9488" }),
    sections: SINGLE_COLUMN_ORDER,
  },
  {
    id: "data-analyst",
    name: "Data Analyst",
    category: "Data Analyst",
    description: "Indigo and cyan, skills-metrics forward for analytics and BI roles.",
    atsFriendly: true,
    layout: { columns: 2, columnRatio: 0.66, pageSize: "a4", headerLayout: "banner" },
    theme: buildTheme({ headingFont: FONT_STACKS.segoe, bodyFont: FONT_STACKS.segoe, primaryColor: "#312e81", accentColor: "#0ea5e9" }),
    sections: twoColumnOrder(["certifications"]),
  },
  {
    id: "fresher",
    name: "Fresher",
    category: "Fresher",
    description: "Bright and friendly, education-first layout for first-job candidates.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "a4", headerLayout: "stacked" },
    theme: buildTheme({ headingFont: FONT_STACKS.segoe, bodyFont: FONT_STACKS.segoe, primaryColor: "#1e40af", accentColor: "#3b82f6" }),
    sections: [
      { type: "name", column: 0 },
      { type: "title", column: 0 },
      { type: "contact", column: 0 },
      { type: "summary", column: 0 },
      { type: "education", column: 0 },
      { type: "projects", column: 0 },
      { type: "skills", column: 0 },
      { type: "certifications", column: 0 },
    ],
  },
  {
    id: "student",
    name: "Student",
    category: "Student",
    description: "Teal and approachable, built around coursework, projects and internships.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "a4", headerLayout: "stacked" },
    theme: buildTheme({ headingFont: FONT_STACKS.segoe, bodyFont: FONT_STACKS.segoe, primaryColor: "#134e4a", accentColor: "#14b8a6" }),
    sections: [
      { type: "name", column: 0 },
      { type: "title", column: 0 },
      { type: "contact", column: 0 },
      { type: "summary", column: 0 },
      { type: "education", column: 0 },
      { type: "projects", column: 0 },
      { type: "experience", column: 0 },
      { type: "skills", column: 0 },
      { type: "interests", column: 0 },
    ],
  },
  {
    id: "marketing",
    name: "Marketing",
    category: "Marketing",
    description: "Magenta and orange, campaign-metrics forward with a bold header band.",
    atsFriendly: false,
    layout: { columns: 2, columnRatio: 0.66, pageSize: "a4", headerLayout: "banner" },
    theme: buildTheme({ headingFont: FONT_STACKS.trebuchet, bodyFont: FONT_STACKS.segoe, primaryColor: "#831843", accentColor: "#f97316" }),
    sections: twoColumnOrder(["interests"]),
  },
  {
    id: "finance",
    name: "Finance",
    category: "Finance",
    description: "Deep green and gold, conservative and figures-forward.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "letter", headerLayout: "stacked" },
    theme: buildTheme({ headingFont: FONT_STACKS.georgia, bodyFont: FONT_STACKS.times, primaryColor: "#052e16", accentColor: "#a16207" }),
    sections: SINGLE_COLUMN_ORDER,
  },
  {
    id: "healthcare",
    name: "Healthcare",
    category: "Healthcare",
    description: "Clinical blue and white, certifications-forward for medical and care roles.",
    atsFriendly: true,
    layout: { columns: 1, columnRatio: 1, pageSize: "letter", headerLayout: "stacked" },
    theme: buildTheme({ headingFont: FONT_STACKS.calibri, bodyFont: FONT_STACKS.calibri, primaryColor: "#0c4a6e", accentColor: "#0284c7" }),
    sections: [
      { type: "name", column: 0 },
      { type: "title", column: 0 },
      { type: "contact", column: 0 },
      { type: "summary", column: 0 },
      { type: "certifications", column: 0 },
      { type: "experience", column: 0 },
      { type: "education", column: 0 },
      { type: "skills", column: 0 },
    ],
  },
  {
    id: "creative",
    name: "Creative",
    category: "Creative",
    description: "Bold two-accent palette and a photo-led header for portfolio-driven fields.",
    atsFriendly: false,
    layout: { columns: 2, columnRatio: 0.62, pageSize: "a4", headerLayout: "split" },
    theme: buildTheme({ headingFont: FONT_STACKS.trebuchet, bodyFont: FONT_STACKS.segoe, primaryColor: "#7c2d12", accentColor: "#f59e0b", backgroundColor: "#fffbf5" }),
    sections: twoColumnOrder(["interests", "languages"]),
  },
];

export function getTemplate(id: string): ResumeTemplate | undefined {
  return RESUME_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): ResumeTemplate[] {
  return RESUME_TEMPLATES.filter((t) => t.category === category);
}
