import type { CanonicalBug } from "./types";

/**
 * The hidden answer key. Every bug here is wired into Brightbasket's actual
 * behavior behind an `isBugActive(id)` check (see toggle-store.ts) so admin
 * can disable a bug and watch the correct behavior come back, with zero
 * changes to business logic elsewhere.
 */
export const BUG_REGISTRY: CanonicalBug[] = [
  {
    id: "BUG-001",
    title: "Login shows a misleading 'invalid password' error for unknown emails",
    module: "Auth",
    category: "Usability",
    severity: "Low",
    priority: "P3",
    description:
      "When a user logs in with an email that isn't registered at all, the error says 'Invalid password' instead of indicating the account doesn't exist.",
    keywords: ["login", "error message", "misleading", "invalid password", "unknown email", "sign in"],
    defaultActive: true,
  },
  {
    id: "BUG-002",
    title: "Registration accepts a one-character password",
    module: "Auth",
    category: "Validation",
    severity: "Medium",
    priority: "P2",
    description: "No minimum length is enforced on the registration password field.",
    keywords: ["register", "password", "minimum length", "weak password", "validation"],
    defaultActive: true,
  },
  {
    id: "BUG-003",
    title: "Logging out does not clear the cart",
    module: "Auth",
    category: "Data",
    severity: "High",
    priority: "P1",
    description:
      "After logout, the cart contents from the previous session remain and are visible to the next user on the same browser.",
    keywords: ["logout", "sign out", "cart", "session", "data leak", "previous user"],
    defaultActive: true,
  },
  {
    id: "BUG-004",
    title: "Search is case- and whitespace-sensitive",
    module: "Catalog",
    category: "Functional",
    severity: "Medium",
    priority: "P2",
    description:
      "Searching 'MOUSE' or '  mouse' returns no results even though a product named 'Mouse' exists.",
    keywords: ["search", "case sensitive", "whitespace", "no results", "catalog"],
    defaultActive: true,
  },
  {
    id: "BUG-005",
    title: "Applying a category filter clears the active search term",
    module: "Catalog",
    category: "Functional",
    severity: "Medium",
    priority: "P2",
    description: "Selecting a category filter silently resets the search box to empty.",
    keywords: ["filter", "search", "category", "reset", "clears"],
    defaultActive: true,
  },
  {
    id: "BUG-006",
    title: "Price sort doesn't re-apply after a filter changes",
    module: "Catalog",
    category: "Functional",
    severity: "Medium",
    priority: "P3",
    description: "'Price: Low to High' stops taking effect once a category filter is also active.",
    keywords: ["sort", "price", "filter", "stale", "low to high"],
    defaultActive: true,
  },
  {
    id: "BUG-007",
    title: "Average rating displays with incorrect rounding",
    module: "Catalog",
    category: "Data",
    severity: "Low",
    priority: "P4",
    description: "A 4.45 average rating displays as 4.5 instead of correctly rounding to 4.4.",
    keywords: ["rating", "rounding", "average", "stars", "display"],
    defaultActive: true,
  },
  {
    id: "BUG-008",
    title: "Out-of-stock products still allow Add to Cart",
    module: "Product Detail",
    category: "Functional",
    severity: "High",
    priority: "P1",
    description: "The Add to Cart button stays enabled and functional for a product with zero stock.",
    keywords: ["out of stock", "add to cart", "inventory", "disabled button", "stock"],
    defaultActive: true,
  },
  {
    id: "BUG-009",
    title: "Product images are missing descriptive alt text",
    module: "Product Detail",
    category: "Accessibility",
    severity: "Medium",
    priority: "P3",
    description: "Screen readers announce the product image generically instead of describing the product.",
    keywords: ["alt text", "accessibility", "screen reader", "image", "aria"],
    defaultActive: true,
  },
  {
    id: "BUG-010",
    title: "Cart quantity accepts negative numbers",
    module: "Cart",
    category: "Boundary",
    severity: "High",
    priority: "P1",
    description: "The quantity stepper/input in the cart can be set below zero.",
    keywords: ["cart", "quantity", "negative", "stepper", "boundary"],
    defaultActive: true,
  },
  {
    id: "BUG-011",
    title: "Cart quantity of 0 leaves a $0 line item instead of removing it",
    module: "Cart",
    category: "Boundary",
    severity: "Medium",
    priority: "P2",
    description: "Setting a cart line's quantity to zero does not remove the item from the cart.",
    keywords: ["cart", "quantity", "zero", "line item", "remove"],
    defaultActive: true,
  },
  {
    id: "BUG-012",
    title: "Checkout price differs from the price shown in the catalog",
    module: "Cart",
    category: "Data",
    severity: "Critical",
    priority: "P1",
    description: "A stale cached price is used at checkout, differing from the catalog/list price for the same product.",
    keywords: ["price", "checkout", "catalog", "mismatch", "stale price"],
    defaultActive: true,
  },
  {
    id: "BUG-013",
    title: "Wishlist allows duplicate entries for the same product",
    module: "Wishlist",
    category: "Functional",
    severity: "Low",
    priority: "P3",
    description: "Clicking 'Add to Wishlist' more than once for the same product creates duplicate rows.",
    keywords: ["wishlist", "duplicate", "add", "same product"],
    defaultActive: true,
  },
  {
    id: "BUG-014",
    title: "Wishlist 'undo remove' does not restore the item",
    module: "Wishlist",
    category: "Functional",
    severity: "Medium",
    priority: "P3",
    description: "The undo action on the remove-from-wishlist toast has no effect.",
    keywords: ["wishlist", "undo", "toast", "remove", "restore"],
    defaultActive: true,
  },
  {
    id: "BUG-015",
    title: "Expired coupon codes still apply their discount",
    module: "Coupons",
    category: "Validation",
    severity: "Critical",
    priority: "P1",
    description: "The coupon expiry date is not checked before applying the discount.",
    keywords: ["coupon", "expired", "discount", "promo code", "expiry"],
    defaultActive: true,
  },
  {
    id: "BUG-016",
    title: "Applying a coupon twice stacks the discount",
    module: "Coupons",
    category: "Functional",
    severity: "High",
    priority: "P1",
    description: "Clicking 'Apply Coupon' a second time applies the discount again instead of being a no-op.",
    keywords: ["coupon", "apply", "twice", "stacked discount", "idempotent"],
    defaultActive: true,
  },
  {
    id: "BUG-017",
    title: "Free-shipping threshold is calculated inconsistently with what's displayed",
    module: "Coupons",
    category: "Data",
    severity: "Medium",
    priority: "P2",
    description: "The free-shipping threshold check uses the pre-discount subtotal while the UI implies it uses the post-discount total.",
    keywords: ["free shipping", "threshold", "subtotal", "discount", "total mismatch"],
    defaultActive: true,
  },
  {
    id: "BUG-018",
    title: "Checkout allows placing an order with an empty address",
    module: "Checkout",
    category: "Validation",
    severity: "Critical",
    priority: "P1",
    description: "The address form has no required-field validation before order placement.",
    keywords: ["checkout", "empty address", "validation", "required field", "place order"],
    defaultActive: true,
  },
  {
    id: "BUG-019",
    title: "Double-clicking Place Order creates duplicate orders",
    module: "Checkout",
    category: "Functional",
    severity: "Critical",
    priority: "P1",
    description: "The Place Order button is not disabled/debounced on submit, so a fast double-click submits two orders.",
    keywords: ["checkout", "place order", "double click", "duplicate order", "submit"],
    defaultActive: true,
  },
  {
    id: "BUG-020",
    title: "Pincode/ZIP field accepts letters and symbols",
    module: "Addresses",
    category: "Validation",
    severity: "Medium",
    priority: "P2",
    description: "The postal code input has no format/pattern validation and accepts any characters.",
    keywords: ["pincode", "zip", "postal code", "validation", "address"],
    defaultActive: true,
  },
  {
    id: "BUG-021",
    title: "No way to change the default address",
    module: "Addresses",
    category: "Usability",
    severity: "Low",
    priority: "P4",
    description: "The oldest saved address is always silently used at checkout with no way to mark another as default.",
    keywords: ["address", "default", "checkout", "usability"],
    defaultActive: true,
  },
  {
    id: "BUG-022",
    title: "Profile update allows saving an empty name",
    module: "Profile",
    category: "Validation",
    severity: "Low",
    priority: "P3",
    description: "The profile name field can be cleared and saved as blank.",
    keywords: ["profile", "name", "empty", "validation", "save"],
    defaultActive: true,
  },
  {
    id: "BUG-023",
    title: "Order history shows the wrong item count",
    module: "Orders",
    category: "Data",
    severity: "Low",
    priority: "P4",
    description: "The item count shown on an order card is off by one from the actual number of line items.",
    keywords: ["order history", "item count", "off by one", "orders"],
    defaultActive: true,
  },
  {
    id: "BUG-024",
    title: "Product grid breaks at narrow (mobile) widths",
    module: "Catalog",
    category: "UI",
    severity: "Medium",
    priority: "P2",
    description: "The product grid overflows horizontally instead of reflowing to a single column on small viewports.",
    keywords: ["responsive", "mobile", "layout", "overflow", "grid", "breaks"],
    defaultActive: true,
  },
];

export function getBugById(id: string): CanonicalBug | undefined {
  return BUG_REGISTRY.find((b) => b.id === id);
}
