import type { DomainCategoryDef } from "../types";

export const BANKING_FINANCE_CATEGORIES: DomainCategoryDef[] = [
  {
    id: "customer-data",
    domainId: "banking-finance",
    name: "Customer Data",
    description: "Bank customer profiles with contact details and KYC status.",
    icon: "User",
    fields: [
      { key: "customerId", label: "Customer ID", type: "id", required: true },
      { key: "fullName", label: "Full Name", type: "fullName", required: true },
      { key: "email", label: "Email", type: "email", required: true },
      { key: "phone", label: "Phone", type: "phone", required: true },
      { key: "dateOfBirth", label: "Date of Birth", type: "dateOfBirth", required: false },
      { key: "gender", label: "Gender", type: "gender", required: false },
      { key: "address", label: "Address", type: "address", required: false },
      { key: "city", label: "City", type: "city", required: false },
      { key: "state", label: "State", type: "state", required: false },
      { key: "postalCode", label: "Postal Code", type: "postalCode", required: false },
      { key: "kycStatus", label: "KYC Status", type: "kycStatus", required: false },
    ],
  },
  {
    id: "account-data",
    domainId: "banking-finance",
    name: "Account Data",
    description: "Bank account records with type, status, and holder details.",
    icon: "Landmark",
    fields: [
      { key: "accountId", label: "Account ID", type: "id", required: true },
      { key: "customerName", label: "Customer Name", type: "fullName", required: true },
      { key: "accountType", label: "Account Type", type: "accountType", required: true },
      { key: "accountNumber", label: "Account Number", type: "accountNumber", required: true },
      { key: "bankName", label: "Bank Name", type: "bankName", required: false },
      { key: "branchName", label: "Branch Name", type: "branchName", required: false },
      { key: "openedDate", label: "Opened Date", type: "date", required: false },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Active", "Inactive", "Closed", "Frozen"] },
    ],
  },
  {
    id: "bank-account-numbers",
    domainId: "banking-finance",
    name: "Bank Account Numbers",
    description: "Standalone account number records with IFSC and holder name.",
    icon: "Hash",
    fields: [
      { key: "accountNumber", label: "Account Number", type: "accountNumber", required: true },
      { key: "ifsc", label: "IFSC Code", type: "ifsc", required: true },
      { key: "bankName", label: "Bank Name", type: "bankName", required: true },
      { key: "accountHolder", label: "Account Holder", type: "fullName", required: true },
      { key: "accountType", label: "Account Type", type: "accountType", required: false },
    ],
  },
  {
    id: "transaction-data",
    domainId: "banking-finance",
    name: "Transaction Data",
    description: "Debit, credit, and transfer transactions with amount and status.",
    icon: "ArrowLeftRight",
    fields: [
      { key: "transactionId", label: "Transaction ID", type: "transactionId", required: true },
      { key: "accountNumber", label: "Account Number", type: "accountNumber", required: true },
      { key: "transactionType", label: "Transaction Type", type: "transactionType", required: true },
      { key: "amount", label: "Amount", type: "amount", required: true },
      { key: "currency", label: "Currency", type: "currencyCode", required: false },
      { key: "transactionDate", label: "Transaction Date", type: "dateTime", required: false },
      { key: "status", label: "Status", type: "paymentStatus", required: false },
    ],
  },
  {
    id: "card-data",
    domainId: "banking-finance",
    name: "Credit/Debit Card Data",
    description: "Synthetic card numbers, type, CVV, and expiry for payment-flow testing.",
    icon: "CreditCard",
    fields: [
      { key: "cardNumber", label: "Card Number", type: "cardNumber", required: true },
      { key: "cardHolder", label: "Card Holder", type: "fullName", required: true },
      { key: "cardType", label: "Card Type", type: "cardType", required: true },
      { key: "cvv", label: "CVV", type: "cvv", required: true },
      { key: "expiry", label: "Expiry", type: "cardExpiry", required: true },
      { key: "billingAddress", label: "Billing Address", type: "address", required: false },
    ],
  },
  {
    id: "loan-data",
    domainId: "banking-finance",
    name: "Loan Data",
    description: "Loan applications with type, amount, tenure, and status.",
    icon: "Coins",
    fields: [
      { key: "loanId", label: "Loan ID", type: "id", required: true },
      { key: "applicantName", label: "Applicant Name", type: "fullName", required: true },
      { key: "loanType", label: "Loan Type", type: "loanType", required: true },
      { key: "loanAmount", label: "Loan Amount", type: "loanAmount", required: true },
      { key: "tenureMonths", label: "Tenure (Months)", type: "tenureMonths", required: false },
      { key: "interestRate", label: "Interest Rate", type: "interestRate", required: false },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Applied", "Approved", "Rejected", "Disbursed", "Closed"] },
    ],
  },
  {
    id: "emi-data",
    domainId: "banking-finance",
    name: "EMI Data",
    description: "Installment schedules linked to a loan, with due date and status.",
    icon: "CalendarDays",
    fields: [
      { key: "emiId", label: "EMI ID", type: "id", required: true },
      { key: "loanId", label: "Loan ID", type: "id", required: true },
      { key: "installmentNumber", label: "Installment #", type: "quantity", required: false },
      { key: "emiAmount", label: "EMI Amount", type: "emiAmount", required: true },
      { key: "dueDate", label: "Due Date", type: "date", required: true },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Paid", "Pending", "Overdue"] },
    ],
  },
  {
    id: "interest-rate-data",
    domainId: "banking-finance",
    name: "Interest Rate Data",
    description: "Interest rates by product type, with effective date and rate type.",
    icon: "Percent",
    fields: [
      { key: "rateId", label: "Rate ID", type: "id", required: true },
      { key: "productType", label: "Product Type", type: "loanType", required: true },
      { key: "interestRate", label: "Interest Rate", type: "interestRate", required: true },
      { key: "effectiveDate", label: "Effective Date", type: "date", required: false },
      { key: "rateType", label: "Rate Type", type: "enum", required: false, enumValues: ["Fixed", "Floating"] },
    ],
  },
  {
    id: "beneficiary-data",
    domainId: "banking-finance",
    name: "Beneficiary Data",
    description: "Registered payees for fund transfers, with account and relationship.",
    icon: "UserCheck",
    fields: [
      { key: "beneficiaryId", label: "Beneficiary ID", type: "id", required: true },
      { key: "beneficiaryName", label: "Beneficiary Name", type: "beneficiaryName", required: true },
      { key: "accountNumber", label: "Account Number", type: "accountNumber", required: true },
      { key: "ifsc", label: "IFSC Code", type: "ifsc", required: true },
      { key: "relationship", label: "Relationship", type: "enum", required: false, enumValues: ["Self", "Family", "Vendor", "Employee", "Other"] },
    ],
  },
  {
    id: "payment-data",
    domainId: "banking-finance",
    name: "Payment Data",
    description: "Payer/payee transfers across methods, with amount and status.",
    icon: "Receipt",
    fields: [
      { key: "paymentId", label: "Payment ID", type: "id", required: true },
      { key: "payer", label: "Payer", type: "fullName", required: true },
      { key: "payee", label: "Payee", type: "beneficiaryName", required: true },
      { key: "amount", label: "Amount", type: "amount", required: true },
      { key: "paymentMethod", label: "Payment Method", type: "paymentMethod", required: false },
      { key: "status", label: "Status", type: "paymentStatus", required: false },
    ],
  },
  {
    id: "upi-data",
    domainId: "banking-finance",
    name: "UPI Data",
    description: "UPI VPAs linked to an account, with transaction reference and status.",
    icon: "Server",
    fields: [
      { key: "upiId", label: "UPI ID", type: "upiId", required: true },
      { key: "holderName", label: "Holder Name", type: "fullName", required: true },
      { key: "linkedAccount", label: "Linked Account", type: "accountNumber", required: false },
      { key: "transactionId", label: "Transaction ID", type: "transactionId", required: false },
      { key: "status", label: "Status", type: "paymentStatus", required: false },
    ],
  },
  {
    id: "ifsc-data",
    domainId: "banking-finance",
    name: "IFSC Data",
    description: "Bank branch IFSC codes with bank, branch, city, and state.",
    icon: "Building2",
    fields: [
      { key: "ifsc", label: "IFSC Code", type: "ifsc", required: true },
      { key: "bankName", label: "Bank Name", type: "bankName", required: true },
      { key: "branchName", label: "Branch Name", type: "branchName", required: true },
      { key: "city", label: "City", type: "city", required: false },
      { key: "state", label: "State", type: "state", required: false },
    ],
  },
  {
    id: "branch-data",
    domainId: "banking-finance",
    name: "Branch Data",
    description: "Bank branch directory with location and IFSC.",
    icon: "Building",
    fields: [
      { key: "branchId", label: "Branch ID", type: "id", required: true },
      { key: "branchName", label: "Branch Name", type: "branchName", required: true },
      { key: "bankName", label: "Bank Name", type: "bankName", required: true },
      { key: "city", label: "City", type: "city", required: true },
      { key: "state", label: "State", type: "state", required: false },
      { key: "ifsc", label: "IFSC Code", type: "ifsc", required: false },
    ],
  },
  {
    id: "currency-data",
    domainId: "banking-finance",
    name: "Currency Data",
    description: "Multi-currency amounts with exchange rate and country.",
    icon: "Coins",
    fields: [
      { key: "currencyCode", label: "Currency Code", type: "currencyCode", required: true },
      { key: "amount", label: "Amount", type: "amount", required: true },
      { key: "exchangeRate", label: "Exchange Rate", type: "interestRate", required: false },
      { key: "country", label: "Country", type: "country", required: false },
    ],
  },
  {
    id: "tax-data",
    domainId: "banking-finance",
    name: "Tax Data",
    description: "Taxpayer records with tax type, amount, and PAN.",
    icon: "FileSignature",
    fields: [
      { key: "taxId", label: "Tax ID", type: "id", required: true },
      { key: "taxpayerName", label: "Taxpayer Name", type: "fullName", required: true },
      { key: "taxType", label: "Tax Type", type: "enum", required: false, enumValues: ["Income Tax", "GST", "VAT", "Service Tax", "Property Tax"] },
      { key: "taxAmount", label: "Tax Amount", type: "taxAmount", required: true },
      { key: "panNumber", label: "PAN Number", type: "panNumber", required: false },
    ],
  },
  {
    id: "kyc-data",
    domainId: "banking-finance",
    name: "KYC Data",
    description: "Know-your-customer verification records by document type.",
    icon: "FileCheck2",
    fields: [
      { key: "kycId", label: "KYC ID", type: "id", required: true },
      { key: "customerName", label: "Customer Name", type: "fullName", required: true },
      { key: "documentType", label: "Document Type", type: "enum", required: false, enumValues: ["Aadhaar", "PAN", "Passport", "Voter ID", "Driving License"] },
      { key: "kycStatus", label: "KYC Status", type: "kycStatus", required: true },
      { key: "verifiedDate", label: "Verified Date", type: "date", required: false },
    ],
  },
];
