import type { DomainCategoryDef } from "../types";

export const ECOMMERCE_CATEGORIES: DomainCategoryDef[] = [
  {
    id: "customer-data",
    domainId: "ecommerce",
    name: "Customer Data",
    description: "Shopper profiles with contact details and location.",
    icon: "User",
    fields: [
      { key: "customerId", label: "Customer ID", type: "id", required: true },
      { key: "fullName", label: "Full Name", type: "fullName", required: true },
      { key: "email", label: "Email", type: "email", required: true },
      { key: "phone", label: "Phone", type: "phone", required: false },
      { key: "city", label: "City", type: "city", required: false },
      { key: "country", label: "Country", type: "country", required: false },
    ],
  },
  {
    id: "product-data",
    domainId: "ecommerce",
    name: "Product Data",
    description: "Catalog items with SKU, category, price, and stock.",
    icon: "Package",
    fields: [
      { key: "productId", label: "Product ID / SKU", type: "sku", required: true },
      { key: "productName", label: "Product Name", type: "productName", required: true },
      { key: "category", label: "Category", type: "productCategory", required: true },
      { key: "price", label: "Price", type: "price", required: true },
      { key: "stockQuantity", label: "Stock Quantity", type: "quantity", required: false },
      { key: "rating", label: "Rating", type: "rating", required: false },
    ],
  },
  {
    id: "order-data",
    domainId: "ecommerce",
    name: "Order Data",
    description: "Customer orders with total amount, status, and payment method.",
    icon: "ShoppingBag",
    fields: [
      { key: "orderId", label: "Order ID", type: "orderId", required: true },
      { key: "customerName", label: "Customer Name", type: "fullName", required: true },
      { key: "orderDate", label: "Order Date", type: "date", required: false },
      { key: "totalAmount", label: "Total Amount", type: "amount", required: true },
      { key: "status", label: "Status", type: "orderStatus", required: true },
      { key: "paymentMethod", label: "Payment Method", type: "paymentMethod", required: false },
    ],
  },
  {
    id: "cart-data",
    domainId: "ecommerce",
    name: "Cart Data",
    description: "Active shopping cart line items.",
    icon: "ShoppingCart",
    fields: [
      { key: "cartId", label: "Cart ID", type: "cartId", required: true },
      { key: "customerName", label: "Customer Name", type: "fullName", required: true },
      { key: "productName", label: "Product Name", type: "productName", required: true },
      { key: "quantity", label: "Quantity", type: "quantity", required: true },
      { key: "itemPrice", label: "Item Price", type: "price", required: false },
    ],
  },
  {
    id: "address-data",
    domainId: "ecommerce",
    name: "Address Data",
    description: "Shipping and billing addresses.",
    icon: "MapPin",
    fields: [
      { key: "addressId", label: "Address ID", type: "id", required: true },
      { key: "fullName", label: "Full Name", type: "fullName", required: true },
      { key: "address", label: "Address", type: "address", required: true },
      { key: "city", label: "City", type: "city", required: true },
      { key: "state", label: "State", type: "state", required: false },
      { key: "postalCode", label: "Postal Code", type: "postalCode", required: false },
      { key: "country", label: "Country", type: "country", required: false },
    ],
  },
  {
    id: "payment-data",
    domainId: "ecommerce",
    name: "Payment Data",
    description: "Order payments across gateways and methods.",
    icon: "CreditCard",
    fields: [
      { key: "paymentId", label: "Payment ID", type: "id", required: true },
      { key: "orderId", label: "Order ID", type: "orderId", required: true },
      { key: "amount", label: "Amount", type: "amount", required: true },
      { key: "paymentMethod", label: "Payment Method", type: "paymentMethod", required: true },
      { key: "status", label: "Status", type: "paymentStatus", required: false },
    ],
  },
  {
    id: "coupon-data",
    domainId: "ecommerce",
    name: "Coupon Data",
    description: "Discount codes with validity window and status.",
    icon: "Tag",
    fields: [
      { key: "couponCode", label: "Coupon Code", type: "couponCode", required: true },
      { key: "discountPercent", label: "Discount %", type: "discountPercent", required: true },
      { key: "validFrom", label: "Valid From", type: "date", required: false },
      { key: "validTo", label: "Valid To", type: "date", required: false },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Active", "Expired", "Used"] },
    ],
  },
  {
    id: "review-data",
    domainId: "ecommerce",
    name: "Review Data",
    description: "Product reviews with rating and reviewer.",
    icon: "Star",
    fields: [
      { key: "reviewId", label: "Review ID", type: "id", required: true },
      { key: "productName", label: "Product Name", type: "productName", required: true },
      { key: "reviewerName", label: "Reviewer Name", type: "fullName", required: true },
      { key: "rating", label: "Rating", type: "reviewRating", required: true },
      { key: "reviewText", label: "Review Text", type: "reviewText", required: false },
    ],
  },
  {
    id: "shipment-data",
    domainId: "ecommerce",
    name: "Shipment Data",
    description: "Carrier tracking and delivery status per order.",
    icon: "Truck",
    fields: [
      { key: "shipmentId", label: "Shipment / Tracking ID", type: "trackingId", required: true },
      { key: "orderId", label: "Order ID", type: "orderId", required: true },
      { key: "carrier", label: "Carrier", type: "enum", required: false, enumValues: ["FedEx", "UPS", "DHL", "BlueDart", "India Post", "Delhivery"] },
      { key: "status", label: "Status", type: "shipmentStatus", required: true },
      { key: "estimatedDelivery", label: "Estimated Delivery", type: "date", required: false },
    ],
  },
  {
    id: "return-data",
    domainId: "ecommerce",
    name: "Return Data",
    description: "Return requests with reason, status, and refund amount.",
    icon: "Undo2",
    fields: [
      { key: "returnId", label: "Return ID", type: "id", required: true },
      { key: "orderId", label: "Order ID", type: "orderId", required: true },
      { key: "reason", label: "Reason", type: "returnReason", required: true },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Requested", "Approved", "Rejected", "Refunded"] },
      { key: "refundAmount", label: "Refund Amount", type: "amount", required: false },
    ],
  },
  {
    id: "invoice-data",
    domainId: "ecommerce",
    name: "Invoice Data",
    description: "Billing invoices with amount, tax, and date.",
    icon: "Receipt",
    fields: [
      { key: "invoiceNumber", label: "Invoice Number", type: "invoiceNumber", required: true },
      { key: "customerName", label: "Customer Name", type: "fullName", required: true },
      { key: "amount", label: "Amount", type: "amount", required: true },
      { key: "taxAmount", label: "Tax Amount", type: "taxAmount", required: false },
      { key: "invoiceDate", label: "Invoice Date", type: "date", required: false },
    ],
  },
];
