import type { DomainCategoryDef } from "../types";

const DEPARTMENTS = ["Cardiology", "Neurology", "Orthopedics", "Pediatrics", "Dermatology", "General Medicine", "ENT", "Oncology"];
const MEDICATIONS = ["Paracetamol", "Amoxicillin", "Ibuprofen", "Metformin", "Atorvastatin", "Omeprazole", "Cetirizine", "Azithromycin"];

export const HEALTHCARE_CATEGORIES: DomainCategoryDef[] = [
  {
    id: "patient-data",
    domainId: "healthcare",
    name: "Patient Data",
    description: "Patient profiles with contact details and blood group.",
    icon: "User",
    fields: [
      { key: "patientId", label: "Patient ID", type: "id", required: true },
      { key: "fullName", label: "Full Name", type: "fullName", required: true },
      { key: "dateOfBirth", label: "Date of Birth", type: "dateOfBirth", required: false },
      { key: "gender", label: "Gender", type: "gender", required: false },
      { key: "phone", label: "Phone", type: "phone", required: false },
      { key: "bloodGroup", label: "Blood Group", type: "enum", required: false, enumValues: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"] },
    ],
  },
  {
    id: "appointment-data",
    domainId: "healthcare",
    name: "Appointment Data",
    description: "Patient-doctor appointments with department and status.",
    icon: "CalendarDays",
    fields: [
      { key: "appointmentId", label: "Appointment ID", type: "id", required: true },
      { key: "patientName", label: "Patient Name", type: "fullName", required: true },
      { key: "doctorName", label: "Doctor Name", type: "fullName", required: true },
      { key: "department", label: "Department", type: "enum", required: false, enumValues: DEPARTMENTS },
      { key: "appointmentDate", label: "Appointment Date", type: "dateTime", required: true },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Scheduled", "Completed", "Cancelled", "No-show"] },
    ],
  },
  {
    id: "doctor-data",
    domainId: "healthcare",
    name: "Doctor Data",
    description: "Doctor directory with specialization and consultation fee.",
    icon: "Stethoscope",
    fields: [
      { key: "doctorId", label: "Doctor ID", type: "id", required: true },
      { key: "fullName", label: "Full Name", type: "fullName", required: true },
      { key: "specialization", label: "Specialization", type: "enum", required: false, enumValues: DEPARTMENTS },
      { key: "yearsExperience", label: "Years of Experience", type: "quantity", required: false },
      { key: "consultationFee", label: "Consultation Fee", type: "price", required: false },
    ],
  },
  {
    id: "prescription-data",
    domainId: "healthcare",
    name: "Prescription Data",
    description: "Prescribed medication with dosage and issue date.",
    icon: "FileSignature",
    fields: [
      { key: "prescriptionId", label: "Prescription ID", type: "id", required: true },
      { key: "patientName", label: "Patient Name", type: "fullName", required: true },
      { key: "doctorName", label: "Doctor Name", type: "fullName", required: false },
      { key: "medication", label: "Medication", type: "enum", required: true, enumValues: MEDICATIONS },
      { key: "dosage", label: "Dosage", type: "enum", required: false, enumValues: ["250mg", "500mg", "650mg", "1000mg"] },
      { key: "issuedDate", label: "Issued Date", type: "date", required: false },
    ],
  },
  {
    id: "diagnosis-data",
    domainId: "healthcare",
    name: "Diagnosis Data",
    description: "Diagnosis codes and descriptions per patient visit.",
    icon: "ClipboardCheck",
    fields: [
      { key: "diagnosisId", label: "Diagnosis ID", type: "id", required: true },
      { key: "patientName", label: "Patient Name", type: "fullName", required: true },
      { key: "diagnosisCode", label: "Diagnosis Code (ICD-style)", type: "enum", required: false, enumValues: ["A09", "E11.9", "I10", "J45.909", "K21.9", "M54.5", "N39.0", "R51"] },
      { key: "description", label: "Description", type: "text", required: false },
      { key: "diagnosisDate", label: "Diagnosis Date", type: "date", required: false },
    ],
  },
  {
    id: "lab-test-data",
    domainId: "healthcare",
    name: "Lab Test Data",
    description: "Diagnostic test orders with result and date.",
    icon: "ClipboardList",
    fields: [
      { key: "testId", label: "Test ID", type: "id", required: true },
      { key: "patientName", label: "Patient Name", type: "fullName", required: true },
      { key: "testType", label: "Test Type", type: "enum", required: true, enumValues: ["Blood Test", "X-Ray", "MRI", "CT Scan", "Urine Test", "ECG", "Ultrasound"] },
      { key: "result", label: "Result", type: "enum", required: false, enumValues: ["Normal", "Abnormal", "Inconclusive"] },
      { key: "testDate", label: "Test Date", type: "date", required: false },
    ],
  },
  {
    id: "insurance-claim-data",
    domainId: "healthcare",
    name: "Insurance Claim Data",
    description: "Health insurance claims filed by patients.",
    icon: "Umbrella",
    fields: [
      { key: "claimId", label: "Claim ID", type: "id", required: true },
      { key: "patientName", label: "Patient Name", type: "fullName", required: true },
      { key: "insuranceProvider", label: "Insurance Provider", type: "enum", required: false, enumValues: ["Aetna", "UnitedHealth", "Cigna", "Star Health", "HDFC Ergo", "ICICI Lombard"] },
      { key: "claimAmount", label: "Claim Amount", type: "amount", required: true },
      { key: "status", label: "Status", type: "paymentStatus", required: false },
    ],
  },
  {
    id: "hospital-bed-data",
    domainId: "healthcare",
    name: "Hospital Bed Data",
    description: "Ward bed occupancy and assignment.",
    icon: "BedDouble",
    fields: [
      { key: "bedId", label: "Bed ID", type: "id", required: true },
      { key: "ward", label: "Ward", type: "enum", required: false, enumValues: ["General", "ICU", "Pediatric", "Maternity", "Surgical", "Emergency"] },
      { key: "patientName", label: "Patient Name", type: "fullName", required: false },
      { key: "status", label: "Status", type: "enum", required: true, enumValues: ["Occupied", "Vacant", "Reserved", "Under Maintenance"] },
    ],
  },
  {
    id: "medication-inventory",
    domainId: "healthcare",
    name: "Medication Inventory",
    description: "Pharmacy stock levels, expiry, and unit price.",
    icon: "Boxes",
    fields: [
      { key: "medicationId", label: "Medication ID", type: "id", required: true },
      { key: "medicationName", label: "Medication Name", type: "enum", required: true, enumValues: MEDICATIONS },
      { key: "stockQuantity", label: "Stock Quantity", type: "quantity", required: false },
      { key: "expiryDate", label: "Expiry Date", type: "date", required: false },
      { key: "unitPrice", label: "Unit Price", type: "price", required: false },
    ],
  },
];
