import type { DomainCategoryDef } from "../types";

export const INSURANCE_CATEGORIES: DomainCategoryDef[] = [
  {
    id: "policyholder-data",
    domainId: "insurance",
    name: "Policyholder Data",
    description: "Policyholder contact and identity details.",
    icon: "User",
    fields: [
      { key: "policyholderId", label: "Policyholder ID", type: "id", required: true },
      { key: "fullName", label: "Full Name", type: "fullName", required: true },
      { key: "email", label: "Email", type: "email", required: false },
      { key: "phone", label: "Phone", type: "phone", required: false },
      { key: "dateOfBirth", label: "Date of Birth", type: "dateOfBirth", required: false },
    ],
  },
  {
    id: "policy-data",
    domainId: "insurance",
    name: "Policy Data",
    description: "Insurance policies with type, premium, and status.",
    icon: "FileCheck2",
    fields: [
      { key: "policyNumber", label: "Policy Number", type: "id", required: true },
      { key: "policyholderName", label: "Policyholder Name", type: "fullName", required: true },
      { key: "policyType", label: "Policy Type", type: "enum", required: true, enumValues: ["Life", "Health", "Motor", "Home", "Travel", "Term"] },
      { key: "premiumAmount", label: "Premium Amount", type: "amount", required: true },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Active", "Lapsed", "Expired", "Cancelled"] },
    ],
  },
  {
    id: "premium-data",
    domainId: "insurance",
    name: "Premium Data",
    description: "Premium payment schedule per policy.",
    icon: "Receipt",
    fields: [
      { key: "premiumId", label: "Premium ID", type: "id", required: true },
      { key: "policyNumber", label: "Policy Number", type: "id", required: true },
      { key: "amount", label: "Amount", type: "amount", required: true },
      { key: "dueDate", label: "Due Date", type: "date", required: false },
      { key: "status", label: "Status", type: "paymentStatus", required: false },
    ],
  },
  {
    id: "claim-data",
    domainId: "insurance",
    name: "Claim Data",
    description: "Insurance claims with amount and review status.",
    icon: "ClipboardCheck",
    fields: [
      { key: "claimId", label: "Claim ID", type: "id", required: true },
      { key: "policyNumber", label: "Policy Number", type: "id", required: true },
      { key: "claimantName", label: "Claimant Name", type: "fullName", required: true },
      { key: "claimAmount", label: "Claim Amount", type: "amount", required: true },
      { key: "claimDate", label: "Claim Date", type: "date", required: false },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Filed", "Under Review", "Approved", "Rejected", "Settled"] },
    ],
  },
  {
    id: "beneficiary-data",
    domainId: "insurance",
    name: "Beneficiary Data",
    description: "Named beneficiaries and their share of a policy payout.",
    icon: "UserCheck",
    fields: [
      { key: "beneficiaryId", label: "Beneficiary ID", type: "id", required: true },
      { key: "beneficiaryName", label: "Beneficiary Name", type: "fullName", required: true },
      { key: "policyNumber", label: "Policy Number", type: "id", required: true },
      { key: "relationship", label: "Relationship", type: "enum", required: false, enumValues: ["Spouse", "Child", "Parent", "Sibling", "Other"] },
      { key: "sharePercent", label: "Share %", type: "percentage", required: false },
    ],
  },
  {
    id: "underwriting-data",
    domainId: "insurance",
    name: "Underwriting Data",
    description: "Risk assessment and decisioning for new applications.",
    icon: "ClipboardList",
    fields: [
      { key: "underwritingId", label: "Underwriting ID", type: "id", required: true },
      { key: "applicantName", label: "Applicant Name", type: "fullName", required: true },
      { key: "riskCategory", label: "Risk Category", type: "enum", required: false, enumValues: ["Low", "Medium", "High"] },
      { key: "sumAssured", label: "Sum Assured", type: "amount", required: true },
      { key: "decision", label: "Decision", type: "enum", required: false, enumValues: ["Approved", "Declined", "Pending"] },
    ],
  },
  {
    id: "agent-data",
    domainId: "insurance",
    name: "Agent Data",
    description: "Insurance agents with region and performance.",
    icon: "UserCheck",
    fields: [
      { key: "agentId", label: "Agent ID", type: "id", required: true },
      { key: "agentName", label: "Agent Name", type: "fullName", required: true },
      { key: "region", label: "Region", type: "state", required: false },
      { key: "policiesSold", label: "Policies Sold", type: "quantity", required: false },
      { key: "commissionEarned", label: "Commission Earned", type: "amount", required: false },
    ],
  },
  {
    id: "vehicle-insurance-data",
    domainId: "insurance",
    name: "Vehicle Insurance Data",
    description: "Motor insurance coverage per vehicle.",
    icon: "FileText",
    fields: [
      { key: "vehicleRegNumber", label: "Vehicle Reg. Number", type: "id", required: true },
      { key: "ownerName", label: "Owner Name", type: "fullName", required: true },
      { key: "vehicleType", label: "Vehicle Type", type: "enum", required: false, enumValues: ["Car", "Motorcycle", "Truck", "Bus", "Van"] },
      { key: "premiumAmount", label: "Premium Amount", type: "amount", required: true },
      { key: "coverageType", label: "Coverage Type", type: "enum", required: false, enumValues: ["Third-Party", "Comprehensive", "Zero Depreciation"] },
    ],
  },
];
