import type { DomainCategoryDef } from "../types";

export const TELECOM_CATEGORIES: DomainCategoryDef[] = [
  {
    id: "subscriber-data",
    domainId: "telecom",
    name: "Subscriber Data",
    description: "Subscriber profiles with plan type and contact details.",
    icon: "User",
    fields: [
      { key: "subscriberId", label: "Subscriber ID", type: "id", required: true },
      { key: "fullName", label: "Full Name", type: "fullName", required: true },
      { key: "phone", label: "Phone", type: "phone", required: true },
      { key: "email", label: "Email", type: "email", required: false },
      { key: "planType", label: "Plan Type", type: "enum", required: false, enumValues: ["Prepaid", "Postpaid"] },
    ],
  },
  {
    id: "sim-data",
    domainId: "telecom",
    name: "SIM Data",
    description: "SIM card / MSISDN records with activation status.",
    icon: "Hash",
    fields: [
      { key: "simNumber", label: "SIM Number", type: "id", required: true },
      { key: "msisdn", label: "MSISDN", type: "phone", required: true },
      { key: "subscriberName", label: "Subscriber Name", type: "fullName", required: false },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Active", "Inactive", "Suspended", "Ported"] },
      { key: "activationDate", label: "Activation Date", type: "date", required: false },
    ],
  },
  {
    id: "call-detail-records",
    domainId: "telecom",
    name: "Call Detail Records",
    description: "Voice/SMS/data call records with duration and timestamp.",
    icon: "ArrowLeftRight",
    fields: [
      { key: "cdrId", label: "CDR ID", type: "id", required: true },
      { key: "callerNumber", label: "Caller Number", type: "phone", required: true },
      { key: "receiverNumber", label: "Receiver Number", type: "phone", required: true },
      { key: "duration", label: "Duration (sec)", type: "quantity", required: false },
      { key: "callType", label: "Call Type", type: "enum", required: false, enumValues: ["Voice", "Video", "SMS", "Data"] },
      { key: "timestamp", label: "Timestamp", type: "dateTime", required: false },
    ],
  },
  {
    id: "plan-data",
    domainId: "telecom",
    name: "Plan Data",
    description: "Rate plans with price, data limit, and validity.",
    icon: "Tag",
    fields: [
      { key: "planId", label: "Plan ID", type: "id", required: true },
      { key: "planName", label: "Plan Name", type: "enum", required: true, enumValues: ["Basic", "Standard", "Premium", "Unlimited", "Data Only"] },
      { key: "monthlyPrice", label: "Monthly Price", type: "price", required: true },
      { key: "dataLimit", label: "Data Limit", type: "enum", required: false, enumValues: ["1GB", "2GB", "5GB", "10GB", "Unlimited"] },
      { key: "validityDays", label: "Validity (Days)", type: "quantity", required: false },
    ],
  },
  {
    id: "billing-data",
    domainId: "telecom",
    name: "Billing Data",
    description: "Monthly bills with amount due and payment status.",
    icon: "Receipt",
    fields: [
      { key: "billId", label: "Bill ID", type: "id", required: true },
      { key: "subscriberName", label: "Subscriber Name", type: "fullName", required: true },
      { key: "billingCycle", label: "Billing Cycle", type: "date", required: false },
      { key: "amountDue", label: "Amount Due", type: "amount", required: true },
      { key: "status", label: "Status", type: "paymentStatus", required: false },
    ],
  },
  {
    id: "usage-data",
    domainId: "telecom",
    name: "Usage Data",
    description: "Per-subscriber data, voice, and SMS usage.",
    icon: "Server",
    fields: [
      { key: "usageId", label: "Usage ID", type: "id", required: true },
      { key: "subscriberName", label: "Subscriber Name", type: "fullName", required: true },
      { key: "dataUsedGB", label: "Data Used (GB)", type: "quantity", required: false },
      { key: "callMinutesUsed", label: "Call Minutes Used", type: "quantity", required: false },
      { key: "smsCount", label: "SMS Count", type: "quantity", required: false },
    ],
  },
  {
    id: "network-tower-data",
    domainId: "telecom",
    name: "Network Tower Data",
    description: "Cell tower status and signal strength by location.",
    icon: "Wifi",
    fields: [
      { key: "towerId", label: "Tower ID", type: "id", required: true },
      { key: "location", label: "Location", type: "city", required: false },
      { key: "status", label: "Status", type: "enum", required: true, enumValues: ["Active", "Maintenance", "Offline"] },
      { key: "signalStrength", label: "Signal Strength (%)", type: "percentage", required: false },
    ],
  },
  {
    id: "complaint-data",
    domainId: "telecom",
    name: "Complaint Data",
    description: "Subscriber complaints by category and resolution status.",
    icon: "MessageSquare",
    fields: [
      { key: "complaintId", label: "Complaint ID", type: "id", required: true },
      { key: "subscriberName", label: "Subscriber Name", type: "fullName", required: true },
      { key: "category", label: "Category", type: "enum", required: false, enumValues: ["Network Issue", "Billing Dispute", "Service Request", "SIM Issue", "Roaming Issue"] },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Open", "In Progress", "Resolved", "Closed"] },
    ],
  },
];
