import type { DomainCategoryDef } from "../types";

export const TRAVEL_HOSPITALITY_CATEGORIES: DomainCategoryDef[] = [
  {
    id: "passenger-data",
    domainId: "travel-hospitality",
    name: "Passenger Data",
    description: "Traveler identity and nationality details.",
    icon: "User",
    fields: [
      { key: "passengerId", label: "Passenger ID", type: "id", required: true },
      { key: "fullName", label: "Full Name", type: "fullName", required: true },
      { key: "passportNumber", label: "Passport Number", type: "id", required: false },
      { key: "nationality", label: "Nationality", type: "country", required: false },
      { key: "dateOfBirth", label: "Date of Birth", type: "dateOfBirth", required: false },
    ],
  },
  {
    id: "flight-booking-data",
    domainId: "travel-hospitality",
    name: "Flight Booking Data",
    description: "Flight reservations with route, class, and status.",
    icon: "Plane",
    fields: [
      { key: "bookingId", label: "Booking ID", type: "id", required: true },
      { key: "passengerName", label: "Passenger Name", type: "fullName", required: true },
      { key: "airline", label: "Airline", type: "enum", required: false, enumValues: ["IndiGo", "Air India", "Emirates", "Qatar Airways", "Lufthansa", "British Airways", "Singapore Airlines", "American Airlines"] },
      { key: "flightNumber", label: "Flight Number", type: "id", required: false },
      { key: "departureCity", label: "Departure City", type: "city", required: false },
      { key: "arrivalCity", label: "Arrival City", type: "city", required: false },
      { key: "departureDate", label: "Departure Date", type: "date", required: true },
      { key: "seatClass", label: "Seat Class", type: "enum", required: false, enumValues: ["Economy", "Premium Economy", "Business", "First"] },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Confirmed", "Pending", "Cancelled", "Checked-in"] },
    ],
  },
  {
    id: "hotel-booking-data",
    domainId: "travel-hospitality",
    name: "Hotel Booking Data",
    description: "Hotel reservations with room type and stay dates.",
    icon: "BedDouble",
    fields: [
      { key: "bookingId", label: "Booking ID", type: "id", required: true },
      { key: "guestName", label: "Guest Name", type: "fullName", required: true },
      { key: "hotelName", label: "Hotel Name", type: "company", required: false },
      { key: "checkInDate", label: "Check-in Date", type: "date", required: true },
      { key: "checkOutDate", label: "Check-out Date", type: "date", required: true },
      { key: "roomType", label: "Room Type", type: "enum", required: false, enumValues: ["Standard", "Deluxe", "Suite", "Executive"] },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Confirmed", "Pending", "Cancelled", "Checked-out"] },
    ],
  },
  {
    id: "itinerary-data",
    domainId: "travel-hospitality",
    name: "Itinerary Data",
    description: "Trip plans with destination and trip type.",
    icon: "CalendarDays",
    fields: [
      { key: "itineraryId", label: "Itinerary ID", type: "id", required: true },
      { key: "travelerName", label: "Traveler Name", type: "fullName", required: true },
      { key: "destination", label: "Destination", type: "city", required: false },
      { key: "startDate", label: "Start Date", type: "date", required: true },
      { key: "endDate", label: "End Date", type: "date", required: false },
      { key: "tripType", label: "Trip Type", type: "enum", required: false, enumValues: ["Business", "Leisure", "Group", "Solo"] },
    ],
  },
  {
    id: "travel-insurance-data",
    domainId: "travel-hospitality",
    name: "Travel Insurance Data",
    description: "Travel policy coverage and premium per trip.",
    icon: "Umbrella",
    fields: [
      { key: "policyId", label: "Policy ID", type: "id", required: true },
      { key: "travelerName", label: "Traveler Name", type: "fullName", required: true },
      { key: "coverageAmount", label: "Coverage Amount", type: "amount", required: true },
      { key: "premium", label: "Premium", type: "amount", required: false },
      { key: "destination", label: "Destination Country", type: "country", required: false },
    ],
  },
  {
    id: "baggage-data",
    domainId: "travel-hospitality",
    name: "Baggage Data",
    description: "Checked-baggage tracking per passenger.",
    icon: "Boxes",
    fields: [
      { key: "baggageId", label: "Baggage ID", type: "id", required: true },
      { key: "passengerName", label: "Passenger Name", type: "fullName", required: true },
      { key: "weightKg", label: "Weight (kg)", type: "quantity", required: false },
      { key: "status", label: "Status", type: "enum", required: true, enumValues: ["Checked-in", "In Transit", "Delivered", "Lost", "Delayed"] },
    ],
  },
  {
    id: "car-rental-data",
    domainId: "travel-hospitality",
    name: "Car Rental Data",
    description: "Vehicle rental bookings with pickup/return dates.",
    icon: "Route",
    fields: [
      { key: "rentalId", label: "Rental ID", type: "id", required: true },
      { key: "renterName", label: "Renter Name", type: "fullName", required: true },
      { key: "vehicleModel", label: "Vehicle Type", type: "enum", required: false, enumValues: ["Sedan", "SUV", "Hatchback", "Convertible", "Van"] },
      { key: "pickupDate", label: "Pickup Date", type: "date", required: true },
      { key: "returnDate", label: "Return Date", type: "date", required: false },
      { key: "rentalAmount", label: "Rental Amount", type: "amount", required: false },
    ],
  },
  {
    id: "visa-application-data",
    domainId: "travel-hospitality",
    name: "Visa Application Data",
    description: "Visa applications with destination and status.",
    icon: "FileSignature",
    fields: [
      { key: "applicationId", label: "Application ID", type: "id", required: true },
      { key: "applicantName", label: "Applicant Name", type: "fullName", required: true },
      { key: "destinationCountry", label: "Destination Country", type: "country", required: false },
      { key: "visaType", label: "Visa Type", type: "enum", required: false, enumValues: ["Tourist", "Business", "Student", "Transit", "Work"] },
      { key: "status", label: "Status", type: "enum", required: false, enumValues: ["Submitted", "Under Review", "Approved", "Rejected"] },
    ],
  },
];
